// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Account struct {
	Name   *string           `json:"name,omitempty" parquet:"name,optional"`
	Tags   []*KeyValueobject `json:"tags,omitempty" parquet:"tags,optional,list"`
	Type   *string           `json:"type,omitempty" parquet:"type,optional"`
	TypeId *int32            `json:"type_id,omitempty" parquet:"type_id,optional"`
	Uid    *string           `json:"uid,omitempty" parquet:"uid,optional"`
	Labels []*string         `json:"labels,omitempty" parquet:"labels,optional,list"`
}
