// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Actor struct {
	AppUid         *string                `json:"app_uid,omitempty" parquet:"app_uid,optional"`
	Authorizations []*AuthorizationResult `json:"authorizations,omitempty" parquet:"authorizations,optional,list"`
	Idp            *IdentityProvider      `json:"idp,omitempty" parquet:"idp,optional"`
	Process        *Process               `json:"process,omitempty" parquet:"process,optional"`
	Session        *Session               `json:"session,omitempty" parquet:"session,optional"`
	User           *User                  `json:"user,omitempty" parquet:"user,optional"`
	AppName        *string                `json:"app_name,omitempty" parquet:"app_name,optional"`
}
