// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Advisory struct {
	CreatedTime    *int64             `json:"created_time,omitempty" parquet:"created_time,optional"`
	IsSuperseded   *bool              `json:"is_superseded,omitempty" parquet:"is_superseded,optional"`
	Product        *Product           `json:"product,omitempty" parquet:"product,optional"`
	References     []*string          `json:"references,omitempty" parquet:"references,optional,list"`
	Size           *int64             `json:"size,omitempty" parquet:"size,optional"`
	Bulletin       *string            `json:"bulletin,omitempty" parquet:"bulletin,optional"`
	Classification *string            `json:"classification,omitempty" parquet:"classification,optional"`
	InstallState   *string            `json:"install_state,omitempty" parquet:"install_state,optional"`
	RelatedCves    []*CVE             `json:"related_cves,omitempty" parquet:"related_cves,optional,list"`
	SrcUrl         *string            `json:"src_url,omitempty" parquet:"src_url,optional"`
	Title          *string            `json:"title,omitempty" parquet:"title,optional"`
	Os             *OperatingSystemOS `json:"os,omitempty" parquet:"os,optional"`
	Uid            string             `json:"uid" parquet:"uid"`
	RelatedCwes    []*CWE             `json:"related_cwes,omitempty" parquet:"related_cwes,optional,list"`
	AvgTimespan    *TimeSpan          `json:"avg_timespan,omitempty" parquet:"avg_timespan,optional"`
	Desc           *string            `json:"desc,omitempty" parquet:"desc,optional"`
	InstallStateId *int32             `json:"install_state_id,omitempty" parquet:"install_state_id,optional"`
	ModifiedTime   *int64             `json:"modified_time,omitempty" parquet:"modified_time,optional"`
}
