// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type AffectedCode struct {
	File        File         `json:"file" parquet:"file"`
	Owner       *User        `json:"owner,omitempty" parquet:"owner,optional"`
	Remediation *Remediation `json:"remediation,omitempty" parquet:"remediation,optional"`
	StartLine   *int32       `json:"start_line,omitempty" parquet:"start_line,optional"`
	EndLine     *int32       `json:"end_line,omitempty" parquet:"end_line,optional"`
}
