// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type AffectedSoftwarePackage struct {
	VendorName     *string      `json:"vendor_name,omitempty" parquet:"vendor_name,optional"`
	FixedInVersion *string      `json:"fixed_in_version,omitempty" parquet:"fixed_in_version,optional"`
	Path           *string      `json:"path,omitempty" parquet:"path,optional"`
	PackageManager *string      `json:"package_manager,omitempty" parquet:"package_manager,optional"`
	Remediation    *Remediation `json:"remediation,omitempty" parquet:"remediation,optional"`
	Name           string       `json:"name" parquet:"name"`
	Type           *string      `json:"type,omitempty" parquet:"type,optional"`
	CpeName        *string      `json:"cpe_name,omitempty" parquet:"cpe_name,optional"`
	Hash           *Fingerprint `json:"hash,omitempty" parquet:"hash,optional"`
	Purl           *string      `json:"purl,omitempty" parquet:"purl,optional"`
	Version        string       `json:"version" parquet:"version"`
	TypeId         *int32       `json:"type_id,omitempty" parquet:"type_id,optional"`
	Architecture   *string      `json:"architecture,omitempty" parquet:"architecture,optional"`
	Epoch          *int32       `json:"epoch,omitempty" parquet:"epoch,optional"`
	License        *string      `json:"license,omitempty" parquet:"license,optional"`
	Release        *string      `json:"release,omitempty" parquet:"release,optional"`
}
