// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Agent struct {
	UidAlt     *string   `json:"uid_alt,omitempty" parquet:"uid_alt,optional"`
	VendorName *string   `json:"vendor_name,omitempty" parquet:"vendor_name,optional"`
	Version    *string   `json:"version,omitempty" parquet:"version,optional"`
	Name       *string   `json:"name,omitempty" parquet:"name,optional"`
	Policies   []*Policy `json:"policies,omitempty" parquet:"policies,optional,list"`
	Type       *string   `json:"type,omitempty" parquet:"type,optional"`
	TypeId     *int32    `json:"type_id,omitempty" parquet:"type_id,optional"`
	Uid        *string   `json:"uid,omitempty" parquet:"uid,optional"`
}
