// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type AirborneBroadcastActivity struct {
	Severity                    *string                       `json:"severity,omitempty" parquet:"severity,optional"`
	TimezoneOffset              *int32                        `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
	Unmapped                    *string                       `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	Traffic                     *NetworkTraffic               `json:"traffic,omitempty" parquet:"traffic,optional"`
	Message                     *string                       `json:"message,omitempty" parquet:"message,optional"`
	Time                        int64                         `json:"time" parquet:"time"`
	Status                      *string                       `json:"status,omitempty" parquet:"status,optional"`
	Count                       *int32                        `json:"count,omitempty" parquet:"count,optional"`
	EndTime                     *int64                        `json:"end_time,omitempty" parquet:"end_time,optional"`
	SrcEndpoint                 *NetworkEndpoint              `json:"src_endpoint,omitempty" parquet:"src_endpoint,optional"`
	UnmannedAerialSystem        UnmannedAerialSystem          `json:"unmanned_aerial_system" parquet:"unmanned_aerial_system"`
	ConnectionInfo              *NetworkConnectionInformation `json:"connection_info,omitempty" parquet:"connection_info,optional"`
	Metadata                    Metadata                      `json:"metadata" parquet:"metadata"`
	UnmannedSystemOperator      User                          `json:"unmanned_system_operator" parquet:"unmanned_system_operator"`
	ClassName                   *string                       `json:"class_name,omitempty" parquet:"class_name,optional"`
	RawData                     *string                       `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	StatusCode                  *string                       `json:"status_code,omitempty" parquet:"status_code,optional"`
	TypeUid                     int64                         `json:"type_uid" parquet:"type_uid"`
	ProxyEndpoint               *NetworkProxyEndpoint         `json:"proxy_endpoint,omitempty" parquet:"proxy_endpoint,optional"`
	Duration                    *int64                        `json:"duration,omitempty" parquet:"duration,optional"`
	Enrichments                 []*Enrichment                 `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	Tls                         *TransportLayerSecurityTLS    `json:"tls,omitempty" parquet:"tls,optional"`
	CategoryName                *string                       `json:"category_name,omitempty" parquet:"category_name,optional"`
	DstEndpoint                 *NetworkEndpoint              `json:"dst_endpoint,omitempty" parquet:"dst_endpoint,optional"`
	TypeName                    *string                       `json:"type_name,omitempty" parquet:"type_name,optional"`
	ProtocolName                *string                       `json:"protocol_name,omitempty" parquet:"protocol_name,optional"`
	Rssi                        *int32                        `json:"rssi,omitempty" parquet:"rssi,optional"`
	ClassUid                    int32                         `json:"class_uid" parquet:"class_uid"`
	SeverityId                  int32                         `json:"severity_id" parquet:"severity_id"`
	StatusDetail                *string                       `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	StatusId                    *int32                        `json:"status_id,omitempty" parquet:"status_id,optional"`
	Aircraft                    *Aircraft                     `json:"aircraft,omitempty" parquet:"aircraft,optional"`
	UnmannedSystemOperatingArea *UnmannedSystemOperatingArea  `json:"unmanned_system_operating_area,omitempty" parquet:"unmanned_system_operating_area,optional"`
	ActivityName                *string                       `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	Observables                 []*Observable                 `json:"observables,omitempty" parquet:"observables,optional,list"`
	ActivityId                  int32                         `json:"activity_id" parquet:"activity_id"`
	CategoryUid                 int32                         `json:"category_uid" parquet:"category_uid"`
	StartTime                   *int64                        `json:"start_time,omitempty" parquet:"start_time,optional"`
}
