// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Aircraft struct {
	Model          *string      `json:"model,omitempty" parquet:"model,optional"`
	SerialNumber   *string      `json:"serial_number,omitempty" parquet:"serial_number,optional"`
	Speed          *string      `json:"speed,omitempty" parquet:"speed,optional"`
	Uid            *string      `json:"uid,omitempty" parquet:"uid,optional"`
	UidAlt         *string      `json:"uid_alt,omitempty" parquet:"uid_alt,optional"`
	Location       *GeoLocation `json:"location,omitempty" parquet:"location,optional"`
	Name           *string      `json:"name,omitempty" parquet:"name,optional"`
	SpeedAccuracy  *string      `json:"speed_accuracy,omitempty" parquet:"speed_accuracy,optional"`
	TrackDirection *string      `json:"track_direction,omitempty" parquet:"track_direction,optional"`
	VerticalSpeed  *string      `json:"vertical_speed,omitempty" parquet:"vertical_speed,optional"`
}
