// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type API struct {
	Group     *Group            `json:"group,omitempty" parquet:"group,optional"`
	Operation string            `json:"operation" parquet:"operation"`
	Request   *RequestElements  `json:"request,omitempty" parquet:"request,optional"`
	Response  *ResponseElements `json:"response,omitempty" parquet:"response,optional"`
	Service   *Service          `json:"service,omitempty" parquet:"service,optional"`
	Version   *string           `json:"version,omitempty" parquet:"version,optional"`
}
