// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type MITREATTCK struct {
	SubTechnique *MITREATTCKSubTechnique `json:"sub_technique,omitempty" parquet:"sub_technique,optional"`
	Tactic       *MITREATTCKTactic       `json:"tactic,omitempty" parquet:"tactic,optional"`
	Technique    *MITREATTCKTechnique    `json:"technique,omitempty" parquet:"technique,optional"`
	Version      *string                 `json:"version,omitempty" parquet:"version,optional"`
}
