// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type AuthenticationFactor struct {
	PhoneNumber       *string   `json:"phone_number,omitempty" parquet:"phone_number,optional"`
	Provider          *string   `json:"provider,omitempty" parquet:"provider,optional"`
	EmailAddr         *string   `json:"email_addr,omitempty" parquet:"email_addr,optional"`
	FactorType        *string   `json:"factor_type,omitempty" parquet:"factor_type,optional"`
	IsHotp            *bool     `json:"is_hotp,omitempty" parquet:"is_hotp,optional"`
	IsTotp            *bool     `json:"is_totp,omitempty" parquet:"is_totp,optional"`
	SecurityQuestions []*string `json:"security_questions,omitempty" parquet:"security_questions,optional,list"`
	Device            *Device   `json:"device,omitempty" parquet:"device,optional"`
	FactorTypeId      int32     `json:"factor_type_id" parquet:"factor_type_id"`
}
