// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type AuthorizeSession struct {
	TimezoneOffset *int32           `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
	TypeUid        int64            `json:"type_uid" parquet:"type_uid"`
	ClassUid       int32            `json:"class_uid" parquet:"class_uid"`
	Enrichments    []*Enrichment    `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	Message        *string          `json:"message,omitempty" parquet:"message,optional"`
	StatusDetail   *string          `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	TypeName       *string          `json:"type_name,omitempty" parquet:"type_name,optional"`
	DstEndpoint    *NetworkEndpoint `json:"dst_endpoint,omitempty" parquet:"dst_endpoint,optional"`
	CategoryName   *string          `json:"category_name,omitempty" parquet:"category_name,optional"`
	HttpResponse   *HTTPResponse    `json:"http_response,omitempty" parquet:"http_response,optional"`
	ActivityId     int32            `json:"activity_id" parquet:"activity_id"`
	Group          *Group           `json:"group,omitempty" parquet:"group,optional"`
	CategoryUid    int32            `json:"category_uid" parquet:"category_uid"`
	ActivityName   *string          `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	Metadata       Metadata         `json:"metadata" parquet:"metadata"`
	SeverityId     int32            `json:"severity_id" parquet:"severity_id"`
	Session        *Session         `json:"session,omitempty" parquet:"session,optional"`
	HttpRequest    *HTTPRequest     `json:"http_request,omitempty" parquet:"http_request,optional"`
	StartTime      *int64           `json:"start_time,omitempty" parquet:"start_time,optional"`
	RawData        *string          `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	Privileges     []*string        `json:"privileges,omitempty" parquet:"privileges,optional,list"`
	Count          *int32           `json:"count,omitempty" parquet:"count,optional"`
	Severity       *string          `json:"severity,omitempty" parquet:"severity,optional"`
	Status         *string          `json:"status,omitempty" parquet:"status,optional"`
	StatusId       *int32           `json:"status_id,omitempty" parquet:"status_id,optional"`
	Unmapped       *string          `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	User           User             `json:"user" parquet:"user"`
	SrcEndpoint    *NetworkEndpoint `json:"src_endpoint,omitempty" parquet:"src_endpoint,optional"`
	Observables    []*Observable    `json:"observables,omitempty" parquet:"observables,optional,list"`
	StatusCode     *string          `json:"status_code,omitempty" parquet:"status_code,optional"`
	ClassName      *string          `json:"class_name,omitempty" parquet:"class_name,optional"`
	EndTime        *int64           `json:"end_time,omitempty" parquet:"end_time,optional"`
	Duration       *int64           `json:"duration,omitempty" parquet:"duration,optional"`
	Time           int64            `json:"time" parquet:"time"`
}
