// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type AuthorizationResult struct {
	Decision *string `json:"decision,omitempty" parquet:"decision,optional"`
	Policy   *Policy `json:"policy,omitempty" parquet:"policy,optional"`
}
