// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type AutonomousSystem struct {
	Name   *string `json:"name,omitempty" parquet:"name,optional"`
	Number *int32  `json:"number,omitempty" parquet:"number,optional"`
}
