// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type DigitalCertificate struct {
	ExpirationTime *int64                    `json:"expiration_time,omitempty" parquet:"expiration_time,optional"`
	Fingerprints   []*Fingerprint            `json:"fingerprints,omitempty" parquet:"fingerprints,optional,list"`
	Issuer         string                    `json:"issuer" parquet:"issuer"`
	Sans           []*SubjectAlternativeName `json:"sans,omitempty" parquet:"sans,optional,list"`
	SerialNumber   string                    `json:"serial_number" parquet:"serial_number"`
	Uid            *string                   `json:"uid,omitempty" parquet:"uid,optional"`
	Version        *string                   `json:"version,omitempty" parquet:"version,optional"`
	CreatedTime    *int64                    `json:"created_time,omitempty" parquet:"created_time,optional"`
	IsSelfSigned   *bool                     `json:"is_self_signed,omitempty" parquet:"is_self_signed,optional"`
	Subject        *string                   `json:"subject,omitempty" parquet:"subject,optional"`
}
