// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type CISControl struct {
	Desc    *string `json:"desc,omitempty" parquet:"desc,optional"`
	Name    string  `json:"name" parquet:"name"`
	Version *string `json:"version,omitempty" parquet:"version,optional"`
}
