// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type CISCSC struct {
	Control string  `json:"control" parquet:"control"`
	Version *string `json:"version,omitempty" parquet:"version,optional"`
}
