// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type ClassifierDetails struct {
	Type string  `json:"type" parquet:"type"`
	Uid  *string `json:"uid,omitempty" parquet:"uid,optional"`
	Name *string `json:"name,omitempty" parquet:"name,optional"`
}
