// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Cloud struct {
	Account        *Account      `json:"account,omitempty" parquet:"account,optional"`
	CloudPartition *string       `json:"cloud_partition,omitempty" parquet:"cloud_partition,optional"`
	Org            *Organization `json:"org,omitempty" parquet:"org,optional"`
	Provider       string        `json:"provider" parquet:"provider"`
	Region         *string       `json:"region,omitempty" parquet:"region,optional"`
	Zone           *string       `json:"zone,omitempty" parquet:"zone,optional"`
}
