// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type CloudResourcesInventoryInfo struct {
	ClassUid       int32              `json:"class_uid" parquet:"class_uid"`
	SeverityId     int32              `json:"severity_id" parquet:"severity_id"`
	Enrichments    []*Enrichment      `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	TypeUid        int64              `json:"type_uid" parquet:"type_uid"`
	Resources      []*ResourceDetails `json:"resources,omitempty" parquet:"resources,optional,list"`
	ActivityName   *string            `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	EndTime        *int64             `json:"end_time,omitempty" parquet:"end_time,optional"`
	Metadata       Metadata           `json:"metadata" parquet:"metadata"`
	Observables    []*Observable      `json:"observables,omitempty" parquet:"observables,optional,list"`
	TimezoneOffset *int32             `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
	Unmapped       *string            `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	Region         *string            `json:"region,omitempty" parquet:"region,optional"`
	Duration       *int64             `json:"duration,omitempty" parquet:"duration,optional"`
	Table          *Table             `json:"table,omitempty" parquet:"table,optional"`
	CategoryUid    int32              `json:"category_uid" parquet:"category_uid"`
	Databucket     *Databucket        `json:"databucket,omitempty" parquet:"databucket,optional"`
	ClassName      *string            `json:"class_name,omitempty" parquet:"class_name,optional"`
	Count          *int32             `json:"count,omitempty" parquet:"count,optional"`
	RawData        *string            `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	Container      *Container         `json:"container,omitempty" parquet:"container,optional"`
	Severity       *string            `json:"severity,omitempty" parquet:"severity,optional"`
	Message        *string            `json:"message,omitempty" parquet:"message,optional"`
	StatusCode     *string            `json:"status_code,omitempty" parquet:"status_code,optional"`
	StatusDetail   *string            `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	ActivityId     int32              `json:"activity_id" parquet:"activity_id"`
	StartTime      *int64             `json:"start_time,omitempty" parquet:"start_time,optional"`
	Database       *Database          `json:"database,omitempty" parquet:"database,optional"`
	Time           int64              `json:"time" parquet:"time"`
	Idp            *IdentityProvider  `json:"idp,omitempty" parquet:"idp,optional"`
	CategoryName   *string            `json:"category_name,omitempty" parquet:"category_name,optional"`
	Status         *string            `json:"status,omitempty" parquet:"status,optional"`
	StatusId       *int32             `json:"status_id,omitempty" parquet:"status_id,optional"`
	TypeName       *string            `json:"type_name,omitempty" parquet:"type_name,optional"`
}
