// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Compliance struct {
	Control              *string           `json:"control,omitempty" parquet:"control,optional"`
	Requirements         []*string         `json:"requirements,omitempty" parquet:"requirements,optional,list"`
	StatusDetails        []*string         `json:"status_details,omitempty" parquet:"status_details,optional,list"`
	ComplianceReferences []*KBArticle      `json:"compliance_references,omitempty" parquet:"compliance_references,optional,list"`
	ControlParameters    []*KeyValueobject `json:"control_parameters,omitempty" parquet:"control_parameters,optional,list"`
	Standards            []string          `json:"standards" parquet:"standards,list"`
	Status               *string           `json:"status,omitempty" parquet:"status,optional"`
	StatusCode           *string           `json:"status_code,omitempty" parquet:"status_code,optional"`
	StatusId             *int32            `json:"status_id,omitempty" parquet:"status_id,optional"`
	ComplianceStandards  []*KBArticle      `json:"compliance_standards,omitempty" parquet:"compliance_standards,optional,list"`
}
