// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Container struct {
	Hash          *Fingerprint      `json:"hash,omitempty" parquet:"hash,optional"`
	Image         *Image            `json:"image,omitempty" parquet:"image,optional"`
	Name          *string           `json:"name,omitempty" parquet:"name,optional"`
	NetworkDriver *string           `json:"network_driver,omitempty" parquet:"network_driver,optional"`
	Orchestrator  *string           `json:"orchestrator,omitempty" parquet:"orchestrator,optional"`
	Runtime       *string           `json:"runtime,omitempty" parquet:"runtime,optional"`
	Labels        []*string         `json:"labels,omitempty" parquet:"labels,optional,list"`
	PodUuid       *string           `json:"pod_uuid,omitempty" parquet:"pod_uuid,optional"`
	Size          *int64            `json:"size,omitempty" parquet:"size,optional"`
	Tags          []*KeyValueobject `json:"tags,omitempty" parquet:"tags,optional,list"`
	Uid           *string           `json:"uid,omitempty" parquet:"uid,optional"`
}
