// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type CVE struct {
	CreatedTime  *int64       `json:"created_time,omitempty" parquet:"created_time,optional"`
	ModifiedTime *int64       `json:"modified_time,omitempty" parquet:"modified_time,optional"`
	Product      *Product     `json:"product,omitempty" parquet:"product,optional"`
	Cvss         []*CVSSScore `json:"cvss,omitempty" parquet:"cvss,optional,list"`
	Desc         *string      `json:"desc,omitempty" parquet:"desc,optional"`
	References   []*string    `json:"references,omitempty" parquet:"references,optional,list"`
	Type         *string      `json:"type,omitempty" parquet:"type,optional"`
	Uid          string       `json:"uid" parquet:"uid"`
	Epss         *EPSS        `json:"epss,omitempty" parquet:"epss,optional"`
	RelatedCwes  []*CWE       `json:"related_cwes,omitempty" parquet:"related_cwes,optional,list"`
	Title        *string      `json:"title,omitempty" parquet:"title,optional"`
}
