// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type CVSSScore struct {
	Metrics      []*Metric `json:"metrics,omitempty" parquet:"metrics,optional,list"`
	OverallScore *float64  `json:"overall_score,omitempty" parquet:"overall_score,optional"`
	SrcUrl       *string   `json:"src_url,omitempty" parquet:"src_url,optional"`
	VectorString *string   `json:"vector_string,omitempty" parquet:"vector_string,optional"`
	VendorName   *string   `json:"vendor_name,omitempty" parquet:"vendor_name,optional"`
	BaseScore    float64   `json:"base_score" parquet:"base_score"`
	Depth        *string   `json:"depth,omitempty" parquet:"depth,optional"`
	Severity     *string   `json:"severity,omitempty" parquet:"severity,optional"`
	Version      string    `json:"version" parquet:"version"`
}
