// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type CWE struct {
	Caption *string `json:"caption,omitempty" parquet:"caption,optional"`
	SrcUrl  *string `json:"src_url,omitempty" parquet:"src_url,optional"`
	Uid     string  `json:"uid" parquet:"uid"`
}
