// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type MITRED3FEND struct {
	D3fTactic    *MITRED3FENDTactic    `json:"d3f_tactic,omitempty" parquet:"d3f_tactic,optional"`
	D3fTechnique *MITREDEFENDTechnique `json:"d3f_technique,omitempty" parquet:"d3f_technique,optional"`
	Version      *string               `json:"version,omitempty" parquet:"version,optional"`
}
