// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Databucket struct {
	Tags                []*KeyValueobject     `json:"tags,omitempty" parquet:"tags,optional,list"`
	Name                *string               `json:"name,omitempty" parquet:"name,optional"`
	TypeId              int32                 `json:"type_id" parquet:"type_id"`
	AgentList           []*Agent              `json:"agent_list,omitempty" parquet:"agent_list,optional,list"`
	Criticality         *string               `json:"criticality,omitempty" parquet:"criticality,optional"`
	CreatedTime         *int64                `json:"created_time,omitempty" parquet:"created_time,optional"`
	IsPublic            *bool                 `json:"is_public,omitempty" parquet:"is_public,optional"`
	CloudPartition      *string               `json:"cloud_partition,omitempty" parquet:"cloud_partition,optional"`
	Namespace           *string               `json:"namespace,omitempty" parquet:"namespace,optional"`
	Labels              []*string             `json:"labels,omitempty" parquet:"labels,optional,list"`
	File                *File                 `json:"file,omitempty" parquet:"file,optional"`
	IsEncrypted         *bool                 `json:"is_encrypted,omitempty" parquet:"is_encrypted,optional"`
	Type                *string               `json:"type,omitempty" parquet:"type,optional"`
	Groups              []*Group              `json:"groups,omitempty" parquet:"groups,optional,list"`
	DataClassifications []*DataClassification `json:"data_classifications,omitempty" parquet:"data_classifications,optional,list"`
	Region              *string               `json:"region,omitempty" parquet:"region,optional"`
	EncryptionDetails   *EncryptionDetails    `json:"encryption_details,omitempty" parquet:"encryption_details,optional"`
	ModifiedTime        *int64                `json:"modified_time,omitempty" parquet:"modified_time,optional"`
	Group               *Group                `json:"group,omitempty" parquet:"group,optional"`
	Data                *string               `json:"data,omitempty" parquet:"data,optional"`
	Hostname            *string               `json:"hostname,omitempty" parquet:"hostname,optional"`
	Ip                  *string               `json:"ip,omitempty" parquet:"ip,optional"`
	Uid                 *string               `json:"uid,omitempty" parquet:"uid,optional"`
	Desc                *string               `json:"desc,omitempty" parquet:"desc,optional"`
	Owner               *User                 `json:"owner,omitempty" parquet:"owner,optional"`
	Size                *int64                `json:"size,omitempty" parquet:"size,optional"`
	Version             *string               `json:"version,omitempty" parquet:"version,optional"`
}
