// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type DataSecurityFinding struct {
	Enrichments      []*Enrichment      `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	StatusDetail     *string            `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	Unmapped         *string            `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	ActivityId       int32              `json:"activity_id" parquet:"activity_id"`
	Database         *Database          `json:"database,omitempty" parquet:"database,optional"`
	SrcEndpoint      *NetworkEndpoint   `json:"src_endpoint,omitempty" parquet:"src_endpoint,optional"`
	TypeName         *string            `json:"type_name,omitempty" parquet:"type_name,optional"`
	EndTime          *int64             `json:"end_time,omitempty" parquet:"end_time,optional"`
	Status           *string            `json:"status,omitempty" parquet:"status,optional"`
	Metadata         Metadata           `json:"metadata" parquet:"metadata"`
	FindingInfo      FindingInformation `json:"finding_info" parquet:"finding_info"`
	ClassName        *string            `json:"class_name,omitempty" parquet:"class_name,optional"`
	ClassUid         int32              `json:"class_uid" parquet:"class_uid"`
	Observables      []*Observable      `json:"observables,omitempty" parquet:"observables,optional,list"`
	RawData          *string            `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	File             *File              `json:"file,omitempty" parquet:"file,optional"`
	Comment          *string            `json:"comment,omitempty" parquet:"comment,optional"`
	SeverityId       int32              `json:"severity_id" parquet:"severity_id"`
	StartTime        *int64             `json:"start_time,omitempty" parquet:"start_time,optional"`
	Duration         *int64             `json:"duration,omitempty" parquet:"duration,optional"`
	Message          *string            `json:"message,omitempty" parquet:"message,optional"`
	Table            *Table             `json:"table,omitempty" parquet:"table,optional"`
	VendorAttributes *VendorAttributes  `json:"vendor_attributes,omitempty" parquet:"vendor_attributes,optional"`
	Count            *int32             `json:"count,omitempty" parquet:"count,optional"`
	Time             int64              `json:"time" parquet:"time"`
	DataSecurity     *DataSecurity      `json:"data_security,omitempty" parquet:"data_security,optional"`
	ActivityName     *string            `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	DstEndpoint      *NetworkEndpoint   `json:"dst_endpoint,omitempty" parquet:"dst_endpoint,optional"`
	Resources        []*ResourceDetails `json:"resources,omitempty" parquet:"resources,optional,list"`
	CategoryName     *string            `json:"category_name,omitempty" parquet:"category_name,optional"`
	StatusCode       *string            `json:"status_code,omitempty" parquet:"status_code,optional"`
	StatusId         *int32             `json:"status_id,omitempty" parquet:"status_id,optional"`
	Severity         *string            `json:"severity,omitempty" parquet:"severity,optional"`
	TypeUid          int64              `json:"type_uid" parquet:"type_uid"`
	CategoryUid      int32              `json:"category_uid" parquet:"category_uid"`
	TimezoneOffset   *int32             `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
	Databucket       *Databucket        `json:"databucket,omitempty" parquet:"databucket,optional"`
}
