// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Database struct {
	DataClassifications []*DataClassification `json:"data_classifications,omitempty" parquet:"data_classifications,optional,list"`
	Desc                *string               `json:"desc,omitempty" parquet:"desc,optional"`
	Groups              []*Group              `json:"groups,omitempty" parquet:"groups,optional,list"`
	Type                *string               `json:"type,omitempty" parquet:"type,optional"`
	TypeId              int32                 `json:"type_id" parquet:"type_id"`
	Uid                 *string               `json:"uid,omitempty" parquet:"uid,optional"`
	CreatedTime         *int64                `json:"created_time,omitempty" parquet:"created_time,optional"`
	ModifiedTime        *int64                `json:"modified_time,omitempty" parquet:"modified_time,optional"`
	Name                *string               `json:"name,omitempty" parquet:"name,optional"`
	Size                *int64                `json:"size,omitempty" parquet:"size,optional"`
}
