// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type DataClassification struct {
	ClassifierDetails *ClassifierDetails  `json:"classifier_details,omitempty" parquet:"classifier_details,optional"`
	Confidentiality   *string             `json:"confidentiality,omitempty" parquet:"confidentiality,optional"`
	ConfidentialityId *int32              `json:"confidentiality_id,omitempty" parquet:"confidentiality_id,optional"`
	DiscoveryDetails  []*DiscoveryDetails `json:"discovery_details,omitempty" parquet:"discovery_details,optional,list"`
	Policy            *Policy             `json:"policy,omitempty" parquet:"policy,optional"`
	Size              *int64              `json:"size,omitempty" parquet:"size,optional"`
	SrcUrl            *string             `json:"src_url,omitempty" parquet:"src_url,optional"`
	Status            *string             `json:"status,omitempty" parquet:"status,optional"`
	Category          *string             `json:"category,omitempty" parquet:"category,optional"`
	CategoryId        *int32              `json:"category_id,omitempty" parquet:"category_id,optional"`
	StatusDetails     []*string           `json:"status_details,omitempty" parquet:"status_details,optional,list"`
	StatusId          *int32              `json:"status_id,omitempty" parquet:"status_id,optional"`
	Total             *int32              `json:"total,omitempty" parquet:"total,optional"`
	Uid               *string             `json:"uid,omitempty" parquet:"uid,optional"`
}
