// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type DatastoreActivity struct {
	Time           int64             `json:"time" parquet:"time"`
	DstEndpoint    *NetworkEndpoint  `json:"dst_endpoint,omitempty" parquet:"dst_endpoint,optional"`
	CategoryUid    int32             `json:"category_uid" parquet:"category_uid"`
	Observables    []*Observable     `json:"observables,omitempty" parquet:"observables,optional,list"`
	ActivityName   *string           `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	TypeUid        int64             `json:"type_uid" parquet:"type_uid"`
	SeverityId     int32             `json:"severity_id" parquet:"severity_id"`
	SrcEndpoint    NetworkEndpoint   `json:"src_endpoint" parquet:"src_endpoint"`
	CategoryName   *string           `json:"category_name,omitempty" parquet:"category_name,optional"`
	ClassName      *string           `json:"class_name,omitempty" parquet:"class_name,optional"`
	Duration       *int64            `json:"duration,omitempty" parquet:"duration,optional"`
	StatusId       *int32            `json:"status_id,omitempty" parquet:"status_id,optional"`
	TimezoneOffset *int32            `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
	TypeName       *string           `json:"type_name,omitempty" parquet:"type_name,optional"`
	QueryInfo      *QueryInformation `json:"query_info,omitempty" parquet:"query_info,optional"`
	RawData        *string           `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	Status         *string           `json:"status,omitempty" parquet:"status,optional"`
	Type           *string           `json:"type,omitempty" parquet:"type,optional"`
	Count          *int32            `json:"count,omitempty" parquet:"count,optional"`
	Enrichments    []*Enrichment     `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	EndTime        *int64            `json:"end_time,omitempty" parquet:"end_time,optional"`
	Metadata       Metadata          `json:"metadata" parquet:"metadata"`
	StatusDetail   *string           `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	HttpResponse   *HTTPResponse     `json:"http_response,omitempty" parquet:"http_response,optional"`
	Severity       *string           `json:"severity,omitempty" parquet:"severity,optional"`
	Unmapped       *string           `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	ActivityId     int32             `json:"activity_id" parquet:"activity_id"`
	Database       *Database         `json:"database,omitempty" parquet:"database,optional"`
	HttpRequest    *HTTPRequest      `json:"http_request,omitempty" parquet:"http_request,optional"`
	Message        *string           `json:"message,omitempty" parquet:"message,optional"`
	StartTime      *int64            `json:"start_time,omitempty" parquet:"start_time,optional"`
	Databucket     *Databucket       `json:"databucket,omitempty" parquet:"databucket,optional"`
	ClassUid       int32             `json:"class_uid" parquet:"class_uid"`
	StatusCode     *string           `json:"status_code,omitempty" parquet:"status_code,optional"`
	Table          *Table            `json:"table,omitempty" parquet:"table,optional"`
	TypeId         *int32            `json:"type_id,omitempty" parquet:"type_id,optional"`
}
