// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type DataSecurity struct {
	DataLifecycleStateId *int32              `json:"data_lifecycle_state_id,omitempty" parquet:"data_lifecycle_state_id,optional"`
	DetectionSystem      *string             `json:"detection_system,omitempty" parquet:"detection_system,optional"`
	CategoryId           *int32              `json:"category_id,omitempty" parquet:"category_id,optional"`
	ConfidentialityId    *int32              `json:"confidentiality_id,omitempty" parquet:"confidentiality_id,optional"`
	Size                 *int64              `json:"size,omitempty" parquet:"size,optional"`
	Category             *string             `json:"category,omitempty" parquet:"category,optional"`
	SrcUrl               *string             `json:"src_url,omitempty" parquet:"src_url,optional"`
	StatusId             *int32              `json:"status_id,omitempty" parquet:"status_id,optional"`
	DetectionPattern     *string             `json:"detection_pattern,omitempty" parquet:"detection_pattern,optional"`
	ClassifierDetails    *ClassifierDetails  `json:"classifier_details,omitempty" parquet:"classifier_details,optional"`
	Confidentiality      *string             `json:"confidentiality,omitempty" parquet:"confidentiality,optional"`
	DetectionSystemId    *int32              `json:"detection_system_id,omitempty" parquet:"detection_system_id,optional"`
	PatternMatch         *string             `json:"pattern_match,omitempty" parquet:"pattern_match,optional"`
	Policy               *Policy             `json:"policy,omitempty" parquet:"policy,optional"`
	DiscoveryDetails     []*DiscoveryDetails `json:"discovery_details,omitempty" parquet:"discovery_details,optional,list"`
	Status               *string             `json:"status,omitempty" parquet:"status,optional"`
	StatusDetails        []*string           `json:"status_details,omitempty" parquet:"status_details,optional,list"`
	Total                *int32              `json:"total,omitempty" parquet:"total,optional"`
	Uid                  *string             `json:"uid,omitempty" parquet:"uid,optional"`
	DataLifecycleState   *string             `json:"data_lifecycle_state,omitempty" parquet:"data_lifecycle_state,optional"`
}
