// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type DCERPC struct {
	Command         *string      `json:"command,omitempty" parquet:"command,optional"`
	CommandResponse *string      `json:"command_response,omitempty" parquet:"command_response,optional"`
	Flags           []string     `json:"flags" parquet:"flags,list"`
	Opnum           *int32       `json:"opnum,omitempty" parquet:"opnum,optional"`
	RpcInterface    RPCInterface `json:"rpc_interface" parquet:"rpc_interface"`
}
