// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type DeviceHardwareInfo struct {
	BiosDate          *string              `json:"bios_date,omitempty" parquet:"bios_date,optional"`
	BiosManufacturer  *string              `json:"bios_manufacturer,omitempty" parquet:"bios_manufacturer,optional"`
	BiosVer           *string              `json:"bios_ver,omitempty" parquet:"bios_ver,optional"`
	CpuBits           *int32               `json:"cpu_bits,omitempty" parquet:"cpu_bits,optional"`
	DesktopDisplay    *Display             `json:"desktop_display,omitempty" parquet:"desktop_display,optional"`
	VendorName        *string              `json:"vendor_name,omitempty" parquet:"vendor_name,optional"`
	CpuArchitecture   *string              `json:"cpu_architecture,omitempty" parquet:"cpu_architecture,optional"`
	CpuArchitectureId *int32               `json:"cpu_architecture_id,omitempty" parquet:"cpu_architecture_id,optional"`
	KeyboardInfo      *KeyboardInformation `json:"keyboard_info,omitempty" parquet:"keyboard_info,optional"`
	RamSize           *int32               `json:"ram_size,omitempty" parquet:"ram_size,optional"`
	CpuCores          *int32               `json:"cpu_cores,omitempty" parquet:"cpu_cores,optional"`
	CpuSpeed          *int32               `json:"cpu_speed,omitempty" parquet:"cpu_speed,optional"`
	Chassis           *string              `json:"chassis,omitempty" parquet:"chassis,optional"`
	CpuCount          *int32               `json:"cpu_count,omitempty" parquet:"cpu_count,optional"`
	CpuType           *string              `json:"cpu_type,omitempty" parquet:"cpu_type,optional"`
	SerialNumber      *string              `json:"serial_number,omitempty" parquet:"serial_number,optional"`
	Uuid              *string              `json:"uuid,omitempty" parquet:"uuid,optional"`
}
