// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type DeviceConfigStateChange struct {
	Severity            *string          `json:"severity,omitempty" parquet:"severity,optional"`
	ClassName           *string          `json:"class_name,omitempty" parquet:"class_name,optional"`
	ClassUid            int32            `json:"class_uid" parquet:"class_uid"`
	Status              *string          `json:"status,omitempty" parquet:"status,optional"`
	ActivityName        *string          `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	SeverityId          int32            `json:"severity_id" parquet:"severity_id"`
	SecurityLevel       *string          `json:"security_level,omitempty" parquet:"security_level,optional"`
	RawData             *string          `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	StatusDetail        *string          `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	StatusCode          *string          `json:"status_code,omitempty" parquet:"status_code,optional"`
	PrevSecurityStates  []*SecurityState `json:"prev_security_states,omitempty" parquet:"prev_security_states,optional,list"`
	Enrichments         []*Enrichment    `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	Observables         []*Observable    `json:"observables,omitempty" parquet:"observables,optional,list"`
	StatusId            *int32           `json:"status_id,omitempty" parquet:"status_id,optional"`
	TypeName            *string          `json:"type_name,omitempty" parquet:"type_name,optional"`
	SecurityLevelId     *int32           `json:"security_level_id,omitempty" parquet:"security_level_id,optional"`
	EndTime             *int64           `json:"end_time,omitempty" parquet:"end_time,optional"`
	PrevSecurityLevel   *string          `json:"prev_security_level,omitempty" parquet:"prev_security_level,optional"`
	State               *string          `json:"state,omitempty" parquet:"state,optional"`
	Metadata            Metadata         `json:"metadata" parquet:"metadata"`
	ActivityId          int32            `json:"activity_id" parquet:"activity_id"`
	Count               *int32           `json:"count,omitempty" parquet:"count,optional"`
	Message             *string          `json:"message,omitempty" parquet:"message,optional"`
	Unmapped            *string          `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	CategoryUid         int32            `json:"category_uid" parquet:"category_uid"`
	Time                int64            `json:"time" parquet:"time"`
	TimezoneOffset      *int32           `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
	StartTime           *int64           `json:"start_time,omitempty" parquet:"start_time,optional"`
	StateId             *int32           `json:"state_id,omitempty" parquet:"state_id,optional"`
	Duration            *int64           `json:"duration,omitempty" parquet:"duration,optional"`
	CategoryName        *string          `json:"category_name,omitempty" parquet:"category_name,optional"`
	TypeUid             int64            `json:"type_uid" parquet:"type_uid"`
	PrevSecurityLevelId *int32           `json:"prev_security_level_id,omitempty" parquet:"prev_security_level_id,optional"`
	SecurityStates      []*SecurityState `json:"security_states,omitempty" parquet:"security_states,optional,list"`
}
