// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type DigitalSignature struct {
	Algorithm    *string             `json:"algorithm,omitempty" parquet:"algorithm,optional"`
	DeveloperUid *string             `json:"developer_uid,omitempty" parquet:"developer_uid,optional"`
	AlgorithmId  int32               `json:"algorithm_id" parquet:"algorithm_id"`
	Certificate  *DigitalCertificate `json:"certificate,omitempty" parquet:"certificate,optional"`
	CreatedTime  *int64              `json:"created_time,omitempty" parquet:"created_time,optional"`
	Digest       *Fingerprint        `json:"digest,omitempty" parquet:"digest,optional"`
	State        *string             `json:"state,omitempty" parquet:"state,optional"`
	StateId      *int32              `json:"state_id,omitempty" parquet:"state_id,optional"`
}
