// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Display struct {
	ColorDepth          *int32 `json:"color_depth,omitempty" parquet:"color_depth,optional"`
	PhysicalHeight      *int32 `json:"physical_height,omitempty" parquet:"physical_height,optional"`
	PhysicalOrientation *int32 `json:"physical_orientation,omitempty" parquet:"physical_orientation,optional"`
	PhysicalWidth       *int32 `json:"physical_width,omitempty" parquet:"physical_width,optional"`
	ScaleFactor         *int32 `json:"scale_factor,omitempty" parquet:"scale_factor,optional"`
}
