// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type DNSQuery struct {
	Hostname  string  `json:"hostname" parquet:"hostname"`
	Opcode    *string `json:"opcode,omitempty" parquet:"opcode,optional"`
	OpcodeId  *int32  `json:"opcode_id,omitempty" parquet:"opcode_id,optional"`
	Class     *string `json:"class,omitempty" parquet:"class,optional"`
	PacketUid *int32  `json:"packet_uid,omitempty" parquet:"packet_uid,optional"`
	Type      *string `json:"type,omitempty" parquet:"type,optional"`
}
