// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type DNSAnswer struct {
	PacketUid *int32    `json:"packet_uid,omitempty" parquet:"packet_uid,optional"`
	Class     *string   `json:"class,omitempty" parquet:"class,optional"`
	FlagIds   []*int32  `json:"flag_ids,omitempty" parquet:"flag_ids,optional,list"`
	Flags     []*string `json:"flags,omitempty" parquet:"flags,optional,list"`
	Rdata     string    `json:"rdata" parquet:"rdata"`
	Ttl       *int32    `json:"ttl,omitempty" parquet:"ttl,optional"`
	Type      *string   `json:"type,omitempty" parquet:"type,optional"`
}
