// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type DomainContact struct {
	Name        *string      `json:"name,omitempty" parquet:"name,optional"`
	PhoneNumber *string      `json:"phone_number,omitempty" parquet:"phone_number,optional"`
	Type        *string      `json:"type,omitempty" parquet:"type,optional"`
	TypeId      int32        `json:"type_id" parquet:"type_id"`
	Uid         *string      `json:"uid,omitempty" parquet:"uid,optional"`
	EmailAddr   *string      `json:"email_addr,omitempty" parquet:"email_addr,optional"`
	Location    *GeoLocation `json:"location,omitempty" parquet:"location,optional"`
}
