// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Email struct {
	From                *string                   `json:"from,omitempty" parquet:"from,optional"`
	ToMailboxes         []*string                 `json:"to_mailboxes,omitempty" parquet:"to_mailboxes,optional,list"`
	Uid                 *string                   `json:"uid,omitempty" parquet:"uid,optional"`
	Cc                  []*string                 `json:"cc,omitempty" parquet:"cc,optional,list"`
	HttpHeaders         []*HTTPHeader             `json:"http_headers,omitempty" parquet:"http_headers,optional,list"`
	MessageUid          *string                   `json:"message_uid,omitempty" parquet:"message_uid,optional"`
	Size                *int64                    `json:"size,omitempty" parquet:"size,optional"`
	Subject             *string                   `json:"subject,omitempty" parquet:"subject,optional"`
	CcMailboxes         []*string                 `json:"cc_mailboxes,omitempty" parquet:"cc_mailboxes,optional,list"`
	FromMailbox         *string                   `json:"from_mailbox,omitempty" parquet:"from_mailbox,optional"`
	RawHeader           *string                   `json:"raw_header,omitempty" parquet:"raw_header,optional"`
	To                  []*string                 `json:"to,omitempty" parquet:"to,optional,list"`
	Urls                []*UniformResourceLocator `json:"urls,omitempty" parquet:"urls,optional,list"`
	XOriginatingIp      []*string                 `json:"x_originating_ip,omitempty" parquet:"x_originating_ip,optional,list"`
	Files               []*File                   `json:"files,omitempty" parquet:"files,optional,list"`
	ReplyToMailboxes    []*string                 `json:"reply_to_mailboxes,omitempty" parquet:"reply_to_mailboxes,optional,list"`
	DataClassifications []*DataClassification     `json:"data_classifications,omitempty" parquet:"data_classifications,optional,list"`
	DeliveredToList     []*string                 `json:"delivered_to_list,omitempty" parquet:"delivered_to_list,optional,list"`
}
