// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type EmailActivity struct {
	ClassName       *string              `json:"class_name,omitempty" parquet:"class_name,optional"`
	StatusCode      *string              `json:"status_code,omitempty" parquet:"status_code,optional"`
	TypeName        *string              `json:"type_name,omitempty" parquet:"type_name,optional"`
	ActivityId      int32                `json:"activity_id" parquet:"activity_id"`
	Metadata        Metadata             `json:"metadata" parquet:"metadata"`
	TypeUid         int64                `json:"type_uid" parquet:"type_uid"`
	StatusDetail    *string              `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	Unmapped        *string              `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	ClassUid        int32                `json:"class_uid" parquet:"class_uid"`
	Severity        *string              `json:"severity,omitempty" parquet:"severity,optional"`
	Attempt         *int32               `json:"attempt,omitempty" parquet:"attempt,optional"`
	ActivityName    *string              `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	CategoryName    *string              `json:"category_name,omitempty" parquet:"category_name,optional"`
	TimezoneOffset  *int32               `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
	Duration        *int64               `json:"duration,omitempty" parquet:"duration,optional"`
	Banner          *string              `json:"banner,omitempty" parquet:"banner,optional"`
	Message         *string              `json:"message,omitempty" parquet:"message,optional"`
	Time            int64                `json:"time" parquet:"time"`
	Direction       *string              `json:"direction,omitempty" parquet:"direction,optional"`
	SeverityId      int32                `json:"severity_id" parquet:"severity_id"`
	StatusId        *int32               `json:"status_id,omitempty" parquet:"status_id,optional"`
	Command         *string              `json:"command,omitempty" parquet:"command,optional"`
	CategoryUid     int32                `json:"category_uid" parquet:"category_uid"`
	ProtocolName    *string              `json:"protocol_name,omitempty" parquet:"protocol_name,optional"`
	SrcEndpoint     *NetworkEndpoint     `json:"src_endpoint,omitempty" parquet:"src_endpoint,optional"`
	RawData         *string              `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	Status          *string              `json:"status,omitempty" parquet:"status,optional"`
	Enrichments     []*Enrichment        `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	StartTime       *int64               `json:"start_time,omitempty" parquet:"start_time,optional"`
	DirectionId     int32                `json:"direction_id" parquet:"direction_id"`
	DstEndpoint     *NetworkEndpoint     `json:"dst_endpoint,omitempty" parquet:"dst_endpoint,optional"`
	Email           Email                `json:"email" parquet:"email"`
	EmailAuth       *EmailAuthentication `json:"email_auth,omitempty" parquet:"email_auth,optional"`
	Count           *int32               `json:"count,omitempty" parquet:"count,optional"`
	EndTime         *int64               `json:"end_time,omitempty" parquet:"end_time,optional"`
	MessageTraceUid *string              `json:"message_trace_uid,omitempty" parquet:"message_trace_uid,optional"`
	Observables     []*Observable        `json:"observables,omitempty" parquet:"observables,optional,list"`
}
