// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type EmailAuthentication struct {
	DkimSignature *string `json:"dkim_signature,omitempty" parquet:"dkim_signature,optional"`
	Dmarc         *string `json:"dmarc,omitempty" parquet:"dmarc,optional"`
	DmarcOverride *string `json:"dmarc_override,omitempty" parquet:"dmarc_override,optional"`
	DmarcPolicy   *string `json:"dmarc_policy,omitempty" parquet:"dmarc_policy,optional"`
	Spf           *string `json:"spf,omitempty" parquet:"spf,optional"`
	Dkim          *string `json:"dkim,omitempty" parquet:"dkim,optional"`
	DkimDomain    *string `json:"dkim_domain,omitempty" parquet:"dkim_domain,optional"`
}
