// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type EncryptionDetails struct {
	Algorithm   *string `json:"algorithm,omitempty" parquet:"algorithm,optional"`
	AlgorithmId *int32  `json:"algorithm_id,omitempty" parquet:"algorithm_id,optional"`
	KeyLength   *int32  `json:"key_length,omitempty" parquet:"key_length,optional"`
	KeyUid      *string `json:"key_uid,omitempty" parquet:"key_uid,optional"`
	Type        *string `json:"type,omitempty" parquet:"type,optional"`
}
