// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type EndpointConnection struct {
	Code            *int32           `json:"code,omitempty" parquet:"code,optional"`
	NetworkEndpoint *NetworkEndpoint `json:"network_endpoint,omitempty" parquet:"network_endpoint,optional"`
}
