// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Endpoint struct {
	NamespacePid  *int32              `json:"namespace_pid,omitempty" parquet:"namespace_pid,optional"`
	AgentList     []*Agent            `json:"agent_list,omitempty" parquet:"agent_list,optional,list"`
	InstanceUid   *string             `json:"instance_uid,omitempty" parquet:"instance_uid,optional"`
	InterfaceName *string             `json:"interface_name,omitempty" parquet:"interface_name,optional"`
	Name          *string             `json:"name,omitempty" parquet:"name,optional"`
	Os            *OperatingSystemOS  `json:"os,omitempty" parquet:"os,optional"`
	Owner         *User               `json:"owner,omitempty" parquet:"owner,optional"`
	SubnetUid     *string             `json:"subnet_uid,omitempty" parquet:"subnet_uid,optional"`
	Uid           *string             `json:"uid,omitempty" parquet:"uid,optional"`
	Domain        *string             `json:"domain,omitempty" parquet:"domain,optional"`
	Hostname      *string             `json:"hostname,omitempty" parquet:"hostname,optional"`
	HwInfo        *DeviceHardwareInfo `json:"hw_info,omitempty" parquet:"hw_info,optional"`
	InterfaceUid  *string             `json:"interface_uid,omitempty" parquet:"interface_uid,optional"`
	Ip            *string             `json:"ip,omitempty" parquet:"ip,optional"`
	Location      *GeoLocation        `json:"location,omitempty" parquet:"location,optional"`
	TypeId        *int32              `json:"type_id,omitempty" parquet:"type_id,optional"`
	VlanUid       *string             `json:"vlan_uid,omitempty" parquet:"vlan_uid,optional"`
	Mac           *string             `json:"mac,omitempty" parquet:"mac,optional"`
	Type          *string             `json:"type,omitempty" parquet:"type,optional"`
	VpcUid        *string             `json:"vpc_uid,omitempty" parquet:"vpc_uid,optional"`
	Zone          *string             `json:"zone,omitempty" parquet:"zone,optional"`
	Container     *Container          `json:"container,omitempty" parquet:"container,optional"`
}
