// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Enrichment struct {
	Reputation  *Reputation `json:"reputation,omitempty" parquet:"reputation,optional"`
	SrcUrl      *string     `json:"src_url,omitempty" parquet:"src_url,optional"`
	Type        *string     `json:"type,omitempty" parquet:"type,optional"`
	Value       string      `json:"value" parquet:"value"`
	Data        string      `json:"data" parquet:"data"`
	ShortDesc   *string     `json:"short_desc,omitempty" parquet:"short_desc,optional"`
	CreatedTime *int64      `json:"created_time,omitempty" parquet:"created_time,optional"`
	Desc        *string     `json:"desc,omitempty" parquet:"desc,optional"`
	Name        string      `json:"name" parquet:"name"`
	Provider    *string     `json:"provider,omitempty" parquet:"provider,optional"`
}
