// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type EntityManagement struct {
	ActivityName   *string          `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	AccessMask     *int32           `json:"access_mask,omitempty" parquet:"access_mask,optional"`
	SrcEndpoint    *NetworkEndpoint `json:"src_endpoint,omitempty" parquet:"src_endpoint,optional"`
	StatusCode     *string          `json:"status_code,omitempty" parquet:"status_code,optional"`
	HttpResponse   *HTTPResponse    `json:"http_response,omitempty" parquet:"http_response,optional"`
	EndTime        *int64           `json:"end_time,omitempty" parquet:"end_time,optional"`
	Severity       *string          `json:"severity,omitempty" parquet:"severity,optional"`
	StatusDetail   *string          `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	TimezoneOffset *int32           `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
	EntityResult   *ManagedEntity   `json:"entity_result,omitempty" parquet:"entity_result,optional"`
	ClassName      *string          `json:"class_name,omitempty" parquet:"class_name,optional"`
	Duration       *int64           `json:"duration,omitempty" parquet:"duration,optional"`
	Status         *string          `json:"status,omitempty" parquet:"status,optional"`
	Observables    []*Observable    `json:"observables,omitempty" parquet:"observables,optional,list"`
	AccessList     []*string        `json:"access_list,omitempty" parquet:"access_list,optional,list"`
	Unmapped       *string          `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	Enrichments    []*Enrichment    `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	TypeUid        int64            `json:"type_uid" parquet:"type_uid"`
	Message        *string          `json:"message,omitempty" parquet:"message,optional"`
	SeverityId     int32            `json:"severity_id" parquet:"severity_id"`
	StartTime      *int64           `json:"start_time,omitempty" parquet:"start_time,optional"`
	Metadata       Metadata         `json:"metadata" parquet:"metadata"`
	Comment        *string          `json:"comment,omitempty" parquet:"comment,optional"`
	Count          *int32           `json:"count,omitempty" parquet:"count,optional"`
	RawData        *string          `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	CategoryName   *string          `json:"category_name,omitempty" parquet:"category_name,optional"`
	Entity         ManagedEntity    `json:"entity" parquet:"entity"`
	HttpRequest    *HTTPRequest     `json:"http_request,omitempty" parquet:"http_request,optional"`
	ClassUid       int32            `json:"class_uid" parquet:"class_uid"`
	Time           int64            `json:"time" parquet:"time"`
	TypeName       *string          `json:"type_name,omitempty" parquet:"type_name,optional"`
	StatusId       *int32           `json:"status_id,omitempty" parquet:"status_id,optional"`
	ActivityId     int32            `json:"activity_id" parquet:"activity_id"`
	CategoryUid    int32            `json:"category_uid" parquet:"category_uid"`
}
