// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type EPSS struct {
	CreatedTime *int64   `json:"created_time,omitempty" parquet:"created_time,optional"`
	Percentile  *float64 `json:"percentile,omitempty" parquet:"percentile,optional"`
	Score       string   `json:"score" parquet:"score"`
	Version     *string  `json:"version,omitempty" parquet:"version,optional"`
}
