// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type EventLogActivity struct {
	StartTime      *int64           `json:"start_time,omitempty" parquet:"start_time,optional"`
	CategoryName   *string          `json:"category_name,omitempty" parquet:"category_name,optional"`
	ActivityId     int32            `json:"activity_id" parquet:"activity_id"`
	Message        *string          `json:"message,omitempty" parquet:"message,optional"`
	LogProvider    *string          `json:"log_provider,omitempty" parquet:"log_provider,optional"`
	Observables    []*Observable    `json:"observables,omitempty" parquet:"observables,optional,list"`
	CategoryUid    int32            `json:"category_uid" parquet:"category_uid"`
	TypeUid        int64            `json:"type_uid" parquet:"type_uid"`
	DstEndpoint    *NetworkEndpoint `json:"dst_endpoint,omitempty" parquet:"dst_endpoint,optional"`
	File           *File            `json:"file,omitempty" parquet:"file,optional"`
	SrcEndpoint    *NetworkEndpoint `json:"src_endpoint,omitempty" parquet:"src_endpoint,optional"`
	StatusCode     *string          `json:"status_code,omitempty" parquet:"status_code,optional"`
	ActivityName   *string          `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	Duration       *int64           `json:"duration,omitempty" parquet:"duration,optional"`
	Severity       *string          `json:"severity,omitempty" parquet:"severity,optional"`
	Count          *int32           `json:"count,omitempty" parquet:"count,optional"`
	EndTime        *int64           `json:"end_time,omitempty" parquet:"end_time,optional"`
	StatusId       *int32           `json:"status_id,omitempty" parquet:"status_id,optional"`
	Unmapped       *string          `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	TimezoneOffset *int32           `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
	Enrichments    []*Enrichment    `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	Time           int64            `json:"time" parquet:"time"`
	LogType        *string          `json:"log_type,omitempty" parquet:"log_type,optional"`
	ClassUid       int32            `json:"class_uid" parquet:"class_uid"`
	LogTypeId      *int32           `json:"log_type_id,omitempty" parquet:"log_type_id,optional"`
	Status         *string          `json:"status,omitempty" parquet:"status,optional"`
	StatusDetail   *string          `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	SeverityId     int32            `json:"severity_id" parquet:"severity_id"`
	ClassName      *string          `json:"class_name,omitempty" parquet:"class_name,optional"`
	Metadata       Metadata         `json:"metadata" parquet:"metadata"`
	RawData        *string          `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	TypeName       *string          `json:"type_name,omitempty" parquet:"type_name,optional"`
	LogName        *string          `json:"log_name,omitempty" parquet:"log_name,optional"`
}
