// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type EvidenceArtifacts struct {
	Database           *Database                     `json:"database,omitempty" parquet:"database,optional"`
	Device             *Device                       `json:"device,omitempty" parquet:"device,optional"`
	Email              *Email                        `json:"email,omitempty" parquet:"email,optional"`
	File               *File                         `json:"file,omitempty" parquet:"file,optional"`
	Job                *Job                          `json:"job,omitempty" parquet:"job,optional"`
	Process            *Process                      `json:"process,omitempty" parquet:"process,optional"`
	Container          *Container                    `json:"container,omitempty" parquet:"container,optional"`
	HttpResponse       *HTTPResponse                 `json:"http_response,omitempty" parquet:"http_response,optional"`
	Script             *Script                       `json:"script,omitempty" parquet:"script,optional"`
	User               *User                         `json:"user,omitempty" parquet:"user,optional"`
	WinService         *WindowsService               `json:"win_service,omitempty" parquet:"win_service,optional"`
	Ja4FingerprintList []*JA4Fingerprint             `json:"ja4_fingerprint_list,omitempty" parquet:"ja4_fingerprint_list,optional,list"`
	Actor              *Actor                        `json:"actor,omitempty" parquet:"actor,optional"`
	Api                *API                          `json:"api,omitempty" parquet:"api,optional"`
	ConnectionInfo     *NetworkConnectionInformation `json:"connection_info,omitempty" parquet:"connection_info,optional"`
	Query              *DNSQuery                     `json:"query,omitempty" parquet:"query,optional"`
	Tls                *TransportLayerSecurityTLS    `json:"tls,omitempty" parquet:"tls,optional"`
	RegKey             *RegistryKey                  `json:"reg_key,omitempty" parquet:"reg_key,optional"`
	Databucket         *Databucket                   `json:"databucket,omitempty" parquet:"databucket,optional"`
	DstEndpoint        *NetworkEndpoint              `json:"dst_endpoint,omitempty" parquet:"dst_endpoint,optional"`
	SrcEndpoint        *NetworkEndpoint              `json:"src_endpoint,omitempty" parquet:"src_endpoint,optional"`
	Url                *UniformResourceLocator       `json:"url,omitempty" parquet:"url,optional"`
	RegValue           *RegistryValue                `json:"reg_value,omitempty" parquet:"reg_value,optional"`
	HttpRequest        *HTTPRequest                  `json:"http_request,omitempty" parquet:"http_request,optional"`
	Data               *string                       `json:"data,omitempty" parquet:"data,optional"`
}
