// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type SchemaExtension struct {
	Name    string `json:"name" parquet:"name"`
	Uid     string `json:"uid" parquet:"uid"`
	Version string `json:"version" parquet:"version"`
}
