// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Feature struct {
	Uid     *string `json:"uid,omitempty" parquet:"uid,optional"`
	Version *string `json:"version,omitempty" parquet:"version,optional"`
	Name    *string `json:"name,omitempty" parquet:"name,optional"`
}
