// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type FileHostingActivity struct {
	StatusId       *int32                        `json:"status_id,omitempty" parquet:"status_id,optional"`
	ConnectionInfo *NetworkConnectionInformation `json:"connection_info,omitempty" parquet:"connection_info,optional"`
	EndTime        *int64                        `json:"end_time,omitempty" parquet:"end_time,optional"`
	ActivityName   *string                       `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	Duration       *int64                        `json:"duration,omitempty" parquet:"duration,optional"`
	StartTime      *int64                        `json:"start_time,omitempty" parquet:"start_time,optional"`
	Enrichments    []*Enrichment                 `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	TimezoneOffset *int32                        `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
	Unmapped       *string                       `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	Metadata       Metadata                      `json:"metadata" parquet:"metadata"`
	FileResult     *File                         `json:"file_result,omitempty" parquet:"file_result,optional"`
	ClassName      *string                       `json:"class_name,omitempty" parquet:"class_name,optional"`
	StatusDetail   *string                       `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	ClassUid       int32                         `json:"class_uid" parquet:"class_uid"`
	RawData        *string                       `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	SrcEndpoint    NetworkEndpoint               `json:"src_endpoint" parquet:"src_endpoint"`
	DstEndpoint    *NetworkEndpoint              `json:"dst_endpoint,omitempty" parquet:"dst_endpoint,optional"`
	CategoryUid    int32                         `json:"category_uid" parquet:"category_uid"`
	SeverityId     int32                         `json:"severity_id" parquet:"severity_id"`
	TypeUid        int64                         `json:"type_uid" parquet:"type_uid"`
	AccessMask     *int32                        `json:"access_mask,omitempty" parquet:"access_mask,optional"`
	ShareTypeId    *int32                        `json:"share_type_id,omitempty" parquet:"share_type_id,optional"`
	Share          *string                       `json:"share,omitempty" parquet:"share,optional"`
	CategoryName   *string                       `json:"category_name,omitempty" parquet:"category_name,optional"`
	Observables    []*Observable                 `json:"observables,omitempty" parquet:"observables,optional,list"`
	Status         *string                       `json:"status,omitempty" parquet:"status,optional"`
	ShareType      *string                       `json:"share_type,omitempty" parquet:"share_type,optional"`
	StatusCode     *string                       `json:"status_code,omitempty" parquet:"status_code,optional"`
	Count          *int32                        `json:"count,omitempty" parquet:"count,optional"`
	TypeName       *string                       `json:"type_name,omitempty" parquet:"type_name,optional"`
	AccessList     []*string                     `json:"access_list,omitempty" parquet:"access_list,optional,list"`
	AccessResult   *string                       `json:"access_result,omitempty" parquet:"access_result,optional"`
	Time           int64                         `json:"time" parquet:"time"`
	ExpirationTime *int64                        `json:"expiration_time,omitempty" parquet:"expiration_time,optional"`
	Message        *string                       `json:"message,omitempty" parquet:"message,optional"`
	ActivityId     int32                         `json:"activity_id" parquet:"activity_id"`
	File           File                          `json:"file" parquet:"file"`
	Severity       *string                       `json:"severity,omitempty" parquet:"severity,optional"`
}
