// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type FileRemediationActivity struct {
	CategoryUid     int32          `json:"category_uid" parquet:"category_uid"`
	Enrichments     []*Enrichment  `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	StatusDetail    *string        `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	Status          *string        `json:"status,omitempty" parquet:"status,optional"`
	File            File           `json:"file" parquet:"file"`
	CategoryName    *string        `json:"category_name,omitempty" parquet:"category_name,optional"`
	Duration        *int64         `json:"duration,omitempty" parquet:"duration,optional"`
	Message         *string        `json:"message,omitempty" parquet:"message,optional"`
	Severity        *string        `json:"severity,omitempty" parquet:"severity,optional"`
	SeverityId      int32          `json:"severity_id" parquet:"severity_id"`
	Unmapped        *string        `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	Metadata        Metadata       `json:"metadata" parquet:"metadata"`
	Time            int64          `json:"time" parquet:"time"`
	CommandUid      string         `json:"command_uid" parquet:"command_uid"`
	Scan            *Scan          `json:"scan,omitempty" parquet:"scan,optional"`
	ClassUid        int32          `json:"class_uid" parquet:"class_uid"`
	Count           *int32         `json:"count,omitempty" parquet:"count,optional"`
	TimezoneOffset  *int32         `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
	ClassName       *string        `json:"class_name,omitempty" parquet:"class_name,optional"`
	EndTime         *int64         `json:"end_time,omitempty" parquet:"end_time,optional"`
	Remediation     *Remediation   `json:"remediation,omitempty" parquet:"remediation,optional"`
	RawData         *string        `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	StatusCode      *string        `json:"status_code,omitempty" parquet:"status_code,optional"`
	TypeName        *string        `json:"type_name,omitempty" parquet:"type_name,optional"`
	TypeUid         int64          `json:"type_uid" parquet:"type_uid"`
	ActivityId      int32          `json:"activity_id" parquet:"activity_id"`
	Countermeasures []*MITRED3FEND `json:"countermeasures,omitempty" parquet:"countermeasures,optional,list"`
	StatusId        *int32         `json:"status_id,omitempty" parquet:"status_id,optional"`
	ActivityName    *string        `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	Observables     []*Observable  `json:"observables,omitempty" parquet:"observables,optional,list"`
	StartTime       *int64         `json:"start_time,omitempty" parquet:"start_time,optional"`
}
