// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type FindingInformation struct {
	Attacks            []*MITREATTCK          `json:"attacks,omitempty" parquet:"attacks,optional,list"`
	FirstSeenTime      *int64                 `json:"first_seen_time,omitempty" parquet:"first_seen_time,optional"`
	Tags               []*KeyValueobject      `json:"tags,omitempty" parquet:"tags,optional,list"`
	UidAlt             *string                `json:"uid_alt,omitempty" parquet:"uid_alt,optional"`
	Analytic           *Analytic              `json:"analytic,omitempty" parquet:"analytic,optional"`
	DataSources        []*string              `json:"data_sources,omitempty" parquet:"data_sources,optional,list"`
	Desc               *string                `json:"desc,omitempty" parquet:"desc,optional"`
	ModifiedTime       *int64                 `json:"modified_time,omitempty" parquet:"modified_time,optional"`
	RelatedEvents      []*RelatedEventFinding `json:"related_events,omitempty" parquet:"related_events,optional,list"`
	RelatedEventsCount *int32                 `json:"related_events_count,omitempty" parquet:"related_events_count,optional"`
	CreatedTime        *int64                 `json:"created_time,omitempty" parquet:"created_time,optional"`
	Product            *Product               `json:"product,omitempty" parquet:"product,optional"`
	SrcUrl             *string                `json:"src_url,omitempty" parquet:"src_url,optional"`
	Title              *string                `json:"title,omitempty" parquet:"title,optional"`
	Types              []*string              `json:"types,omitempty" parquet:"types,optional,list"`
	Uid                string                 `json:"uid" parquet:"uid"`
	KillChain          []*KillChainPhase      `json:"kill_chain,omitempty" parquet:"kill_chain,optional,list"`
	LastSeenTime       *int64                 `json:"last_seen_time,omitempty" parquet:"last_seen_time,optional"`
	RelatedAnalytics   []*Analytic            `json:"related_analytics,omitempty" parquet:"related_analytics,optional,list"`
}
