// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Finding struct {
	LastSeenTime   *int64                 `json:"last_seen_time,omitempty" parquet:"last_seen_time,optional"`
	SupportingData *string                `json:"supporting_data,omitempty" parquet:"supporting_data,optional"`
	Types          []*string              `json:"types,omitempty" parquet:"types,optional,list"`
	CreatedTime    *int64                 `json:"created_time,omitempty" parquet:"created_time,optional"`
	Desc           *string                `json:"desc,omitempty" parquet:"desc,optional"`
	ModifiedTime   *int64                 `json:"modified_time,omitempty" parquet:"modified_time,optional"`
	Product        *Product               `json:"product,omitempty" parquet:"product,optional"`
	RelatedEvents  []*RelatedEventFinding `json:"related_events,omitempty" parquet:"related_events,optional,list"`
	Remediation    *Remediation           `json:"remediation,omitempty" parquet:"remediation,optional"`
	Title          string                 `json:"title" parquet:"title"`
	FirstSeenTime  *int64                 `json:"first_seen_time,omitempty" parquet:"first_seen_time,optional"`
	SrcUrl         *string                `json:"src_url,omitempty" parquet:"src_url,optional"`
	Uid            string                 `json:"uid" parquet:"uid"`
}
