// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Fingerprint struct {
	Algorithm   *string `json:"algorithm,omitempty" parquet:"algorithm,optional"`
	AlgorithmId int32   `json:"algorithm_id" parquet:"algorithm_id"`
	Value       string  `json:"value" parquet:"value"`
}
