// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type FirewallRule struct {
	Uid           *string   `json:"uid,omitempty" parquet:"uid,optional"`
	Duration      *int64    `json:"duration,omitempty" parquet:"duration,optional"`
	MatchDetails  []*string `json:"match_details,omitempty" parquet:"match_details,optional,list"`
	MatchLocation *string   `json:"match_location,omitempty" parquet:"match_location,optional"`
	RateLimit     *int32    `json:"rate_limit,omitempty" parquet:"rate_limit,optional"`
	Desc          *string   `json:"desc,omitempty" parquet:"desc,optional"`
	Name          *string   `json:"name,omitempty" parquet:"name,optional"`
	Version       *string   `json:"version,omitempty" parquet:"version,optional"`
	Condition     *string   `json:"condition,omitempty" parquet:"condition,optional"`
	Sensitivity   *string   `json:"sensitivity,omitempty" parquet:"sensitivity,optional"`
	Category      *string   `json:"category,omitempty" parquet:"category,optional"`
	Type          *string   `json:"type,omitempty" parquet:"type,optional"`
}
