// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Group struct {
	Name       *string   `json:"name,omitempty" parquet:"name,optional"`
	Privileges []*string `json:"privileges,omitempty" parquet:"privileges,optional,list"`
	Type       *string   `json:"type,omitempty" parquet:"type,optional"`
	Uid        *string   `json:"uid,omitempty" parquet:"uid,optional"`
	Desc       *string   `json:"desc,omitempty" parquet:"desc,optional"`
	Domain     *string   `json:"domain,omitempty" parquet:"domain,optional"`
}
