// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type HASSH struct {
	Fingerprint Fingerprint `json:"fingerprint" parquet:"fingerprint"`
	Algorithm   *string     `json:"algorithm,omitempty" parquet:"algorithm,optional"`
}
