// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type HTTPCookie struct {
	Domain         *string `json:"domain,omitempty" parquet:"domain,optional"`
	ExpirationTime *int64  `json:"expiration_time,omitempty" parquet:"expiration_time,optional"`
	IsHttpOnly     *bool   `json:"is_http_only,omitempty" parquet:"is_http_only,optional"`
	IsSecure       *bool   `json:"is_secure,omitempty" parquet:"is_secure,optional"`
	Path           *string `json:"path,omitempty" parquet:"path,optional"`
	Samesite       *string `json:"samesite,omitempty" parquet:"samesite,optional"`
	Value          string  `json:"value" parquet:"value"`
	Name           string  `json:"name" parquet:"name"`
}
