// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type HTTPResponse struct {
	Message     *string       `json:"message,omitempty" parquet:"message,optional"`
	Status      *string       `json:"status,omitempty" parquet:"status,optional"`
	BodyLength  *int32        `json:"body_length,omitempty" parquet:"body_length,optional"`
	Code        int32         `json:"code" parquet:"code"`
	ContentType *string       `json:"content_type,omitempty" parquet:"content_type,optional"`
	HttpHeaders []*HTTPHeader `json:"http_headers,omitempty" parquet:"http_headers,optional,list"`
	Latency     *int32        `json:"latency,omitempty" parquet:"latency,optional"`
	Length      *int32        `json:"length,omitempty" parquet:"length,optional"`
}
