// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type HTTPRequest struct {
	Args          *string                 `json:"args,omitempty" parquet:"args,optional"`
	BodyLength    *int32                  `json:"body_length,omitempty" parquet:"body_length,optional"`
	HttpMethod    *string                 `json:"http_method,omitempty" parquet:"http_method,optional"`
	Referrer      *string                 `json:"referrer,omitempty" parquet:"referrer,optional"`
	UserAgent     *string                 `json:"user_agent,omitempty" parquet:"user_agent,optional"`
	Version       *string                 `json:"version,omitempty" parquet:"version,optional"`
	XForwardedFor []*string               `json:"x_forwarded_for,omitempty" parquet:"x_forwarded_for,optional,list"`
	HttpHeaders   []*HTTPHeader           `json:"http_headers,omitempty" parquet:"http_headers,optional,list"`
	Length        *int32                  `json:"length,omitempty" parquet:"length,optional"`
	Uid           *string                 `json:"uid,omitempty" parquet:"uid,optional"`
	Url           *UniformResourceLocator `json:"url,omitempty" parquet:"url,optional"`
}
