// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type IdentityProvider struct {
	TenantUid    *string                 `json:"tenant_uid,omitempty" parquet:"tenant_uid,optional"`
	UrlString    *string                 `json:"url_string,omitempty" parquet:"url_string,optional"`
	AuthFactors  []*AuthenticationFactor `json:"auth_factors,omitempty" parquet:"auth_factors,optional,list"`
	Fingerprint  *Fingerprint            `json:"fingerprint,omitempty" parquet:"fingerprint,optional"`
	Issuer       *string                 `json:"issuer,omitempty" parquet:"issuer,optional"`
	Name         *string                 `json:"name,omitempty" parquet:"name,optional"`
	ProtocolName *string                 `json:"protocol_name,omitempty" parquet:"protocol_name,optional"`
	Scim         *SCIM                   `json:"scim,omitempty" parquet:"scim,optional"`
	State        *string                 `json:"state,omitempty" parquet:"state,optional"`
	Uid          *string                 `json:"uid,omitempty" parquet:"uid,optional"`
	Domain       *string                 `json:"domain,omitempty" parquet:"domain,optional"`
	HasMfa       *bool                   `json:"has_mfa,omitempty" parquet:"has_mfa,optional"`
	Sso          *SSO                    `json:"sso,omitempty" parquet:"sso,optional"`
	StateId      *int32                  `json:"state_id,omitempty" parquet:"state_id,optional"`
}
