// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Image struct {
	Uid    string            `json:"uid" parquet:"uid"`
	Labels []*string         `json:"labels,omitempty" parquet:"labels,optional,list"`
	Name   *string           `json:"name,omitempty" parquet:"name,optional"`
	Path   *string           `json:"path,omitempty" parquet:"path,optional"`
	Tags   []*KeyValueobject `json:"tags,omitempty" parquet:"tags,optional,list"`
}
