// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type IncidentFinding struct {
	StartTime        *int64               `json:"start_time,omitempty" parquet:"start_time,optional"`
	Unmapped         *string              `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	VendorAttributes *VendorAttributes    `json:"vendor_attributes,omitempty" parquet:"vendor_attributes,optional"`
	CategoryUid      int32                `json:"category_uid" parquet:"category_uid"`
	ClassName        *string              `json:"class_name,omitempty" parquet:"class_name,optional"`
	ClassUid         int32                `json:"class_uid" parquet:"class_uid"`
	Count            *int32               `json:"count,omitempty" parquet:"count,optional"`
	TypeName         *string              `json:"type_name,omitempty" parquet:"type_name,optional"`
	Enrichments      []*Enrichment        `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	ActivityId       int32                `json:"activity_id" parquet:"activity_id"`
	ActivityName     *string              `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	Duration         *int64               `json:"duration,omitempty" parquet:"duration,optional"`
	EndTime          *int64               `json:"end_time,omitempty" parquet:"end_time,optional"`
	Metadata         Metadata             `json:"metadata" parquet:"metadata"`
	TypeUid          int64                `json:"type_uid" parquet:"type_uid"`
	Message          *string              `json:"message,omitempty" parquet:"message,optional"`
	StatusCode       *string              `json:"status_code,omitempty" parquet:"status_code,optional"`
	Status           *string              `json:"status,omitempty" parquet:"status,optional"`
	Observables      []*Observable        `json:"observables,omitempty" parquet:"observables,optional,list"`
	RawData          *string              `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	Severity         *string              `json:"severity,omitempty" parquet:"severity,optional"`
	Comment          *string              `json:"comment,omitempty" parquet:"comment,optional"`
	StatusDetail     *string              `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	Desc             *string              `json:"desc,omitempty" parquet:"desc,optional"`
	FindingInfoList  []FindingInformation `json:"finding_info_list" parquet:"finding_info_list,list"`
	StatusId         int32                `json:"status_id" parquet:"status_id"`
	CategoryName     *string              `json:"category_name,omitempty" parquet:"category_name,optional"`
	SeverityId       int32                `json:"severity_id" parquet:"severity_id"`
	Time             int64                `json:"time" parquet:"time"`
	TimezoneOffset   *int32               `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
}
