// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type JA4Fingerprint struct {
	TypeId   int32   `json:"type_id" parquet:"type_id"`
	Value    string  `json:"value" parquet:"value"`
	SectionA *string `json:"section_a,omitempty" parquet:"section_a,optional"`
	SectionB *string `json:"section_b,omitempty" parquet:"section_b,optional"`
	SectionC *string `json:"section_c,omitempty" parquet:"section_c,optional"`
	SectionD *string `json:"section_d,omitempty" parquet:"section_d,optional"`
	Type     *string `json:"type,omitempty" parquet:"type,optional"`
}
