// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Job struct {
	CreatedTime *int64  `json:"created_time,omitempty" parquet:"created_time,optional"`
	Desc        *string `json:"desc,omitempty" parquet:"desc,optional"`
	File        File    `json:"file" parquet:"file"`
	LastRunTime *int64  `json:"last_run_time,omitempty" parquet:"last_run_time,optional"`
	NextRunTime *int64  `json:"next_run_time,omitempty" parquet:"next_run_time,optional"`
	RunStateId  *int32  `json:"run_state_id,omitempty" parquet:"run_state_id,optional"`
	User        *User   `json:"user,omitempty" parquet:"user,optional"`
	CmdLine     *string `json:"cmd_line,omitempty" parquet:"cmd_line,optional"`
	Name        string  `json:"name" parquet:"name"`
	RunState    *string `json:"run_state,omitempty" parquet:"run_state,optional"`
}
