// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type KBArticle struct {
	AvgTimespan    *TimeSpan          `json:"avg_timespan,omitempty" parquet:"avg_timespan,optional"`
	Bulletin       *string            `json:"bulletin,omitempty" parquet:"bulletin,optional"`
	CreatedTime    *int64             `json:"created_time,omitempty" parquet:"created_time,optional"`
	InstallState   *string            `json:"install_state,omitempty" parquet:"install_state,optional"`
	Uid            string             `json:"uid" parquet:"uid"`
	Size           *int64             `json:"size,omitempty" parquet:"size,optional"`
	Classification *string            `json:"classification,omitempty" parquet:"classification,optional"`
	IsSuperseded   *bool              `json:"is_superseded,omitempty" parquet:"is_superseded,optional"`
	SrcUrl         *string            `json:"src_url,omitempty" parquet:"src_url,optional"`
	InstallStateId *int32             `json:"install_state_id,omitempty" parquet:"install_state_id,optional"`
	Os             *OperatingSystemOS `json:"os,omitempty" parquet:"os,optional"`
	Product        *Product           `json:"product,omitempty" parquet:"product,optional"`
	Severity       *string            `json:"severity,omitempty" parquet:"severity,optional"`
	Title          *string            `json:"title,omitempty" parquet:"title,optional"`
}
