// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type KernelResource struct {
	SystemCall *string `json:"system_call,omitempty" parquet:"system_call,optional"`
	Type       *string `json:"type,omitempty" parquet:"type,optional"`
	TypeId     int32   `json:"type_id" parquet:"type_id"`
	IsSystem   *bool   `json:"is_system,omitempty" parquet:"is_system,optional"`
	Name       string  `json:"name" parquet:"name"`
	Path       *string `json:"path,omitempty" parquet:"path,optional"`
}
