// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type KeyValueobject struct {
	Values []*string `json:"values,omitempty" parquet:"values,optional,list"`
	Name   string    `json:"name" parquet:"name"`
	Value  *string   `json:"value,omitempty" parquet:"value,optional"`
}
