// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type KeyboardInformation struct {
	FunctionKeys    *int32  `json:"function_keys,omitempty" parquet:"function_keys,optional"`
	Ime             *string `json:"ime,omitempty" parquet:"ime,optional"`
	KeyboardLayout  *string `json:"keyboard_layout,omitempty" parquet:"keyboard_layout,optional"`
	KeyboardSubtype *int32  `json:"keyboard_subtype,omitempty" parquet:"keyboard_subtype,optional"`
	KeyboardType    *string `json:"keyboard_type,omitempty" parquet:"keyboard_type,optional"`
}
