// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type KillChainPhase struct {
	PhaseId int32   `json:"phase_id" parquet:"phase_id"`
	Phase   *string `json:"phase,omitempty" parquet:"phase,optional"`
}
