// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type LDAPPerson struct {
	LeaveTime      *int64            `json:"leave_time,omitempty" parquet:"leave_time,optional"`
	Surname        *string           `json:"surname,omitempty" parquet:"surname,optional"`
	Tags           []*KeyValueobject `json:"tags,omitempty" parquet:"tags,optional,list"`
	CostCenter     *string           `json:"cost_center,omitempty" parquet:"cost_center,optional"`
	EmailAddrs     []*string         `json:"email_addrs,omitempty" parquet:"email_addrs,optional,list"`
	GivenName      *string           `json:"given_name,omitempty" parquet:"given_name,optional"`
	LdapCn         *string           `json:"ldap_cn,omitempty" parquet:"ldap_cn,optional"`
	Location       *GeoLocation      `json:"location,omitempty" parquet:"location,optional"`
	ModifiedTime   *int64            `json:"modified_time,omitempty" parquet:"modified_time,optional"`
	CreatedTime    *int64            `json:"created_time,omitempty" parquet:"created_time,optional"`
	EmployeeUid    *string           `json:"employee_uid,omitempty" parquet:"employee_uid,optional"`
	DeletedTime    *int64            `json:"deleted_time,omitempty" parquet:"deleted_time,optional"`
	JobTitle       *string           `json:"job_title,omitempty" parquet:"job_title,optional"`
	Manager        *User             `json:"manager,omitempty" parquet:"manager,optional"`
	OfficeLocation *string           `json:"office_location,omitempty" parquet:"office_location,optional"`
	PhoneNumber    *string           `json:"phone_number,omitempty" parquet:"phone_number,optional"`
	HireTime       *int64            `json:"hire_time,omitempty" parquet:"hire_time,optional"`
	Labels         []*string         `json:"labels,omitempty" parquet:"labels,optional,list"`
	LastLoginTime  *int64            `json:"last_login_time,omitempty" parquet:"last_login_time,optional"`
	LdapDn         *string           `json:"ldap_dn,omitempty" parquet:"ldap_dn,optional"`
}
