// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type LoadBalancer struct {
	Ip                  *string               `json:"ip,omitempty" parquet:"ip,optional"`
	Message             *string               `json:"message,omitempty" parquet:"message,optional"`
	Uid                 *string               `json:"uid,omitempty" parquet:"uid,optional"`
	DstEndpoint         *NetworkEndpoint      `json:"dst_endpoint,omitempty" parquet:"dst_endpoint,optional"`
	ErrorMessage        *string               `json:"error_message,omitempty" parquet:"error_message,optional"`
	Metrics             []*Metric             `json:"metrics,omitempty" parquet:"metrics,optional,list"`
	Name                *string               `json:"name,omitempty" parquet:"name,optional"`
	StatusDetail        *string               `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	Classification      *string               `json:"classification,omitempty" parquet:"classification,optional"`
	Code                *int32                `json:"code,omitempty" parquet:"code,optional"`
	EndpointConnections []*EndpointConnection `json:"endpoint_connections,omitempty" parquet:"endpoint_connections,optional,list"`
}
