// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type GeoLocation struct {
	AerialHeight             *string  `json:"aerial_height,omitempty" parquet:"aerial_height,optional"`
	Country                  *string  `json:"country,omitempty" parquet:"country,optional"`
	Geohash                  *string  `json:"geohash,omitempty" parquet:"geohash,optional"`
	Lat                      *float64 `json:"lat,omitempty" parquet:"lat,optional"`
	Provider                 *string  `json:"provider,omitempty" parquet:"provider,optional"`
	Region                   *string  `json:"region,omitempty" parquet:"region,optional"`
	GeodeticAltitude         *string  `json:"geodetic_altitude,omitempty" parquet:"geodetic_altitude,optional"`
	GeodeticVerticalAccuracy *string  `json:"geodetic_vertical_accuracy,omitempty" parquet:"geodetic_vertical_accuracy,optional"`
	HorizontalAccuracy       *string  `json:"horizontal_accuracy,omitempty" parquet:"horizontal_accuracy,optional"`
	PostalCode               *string  `json:"postal_code,omitempty" parquet:"postal_code,optional"`
	Continent                *string  `json:"continent,omitempty" parquet:"continent,optional"`
	IsOnPremises             *bool    `json:"is_on_premises,omitempty" parquet:"is_on_premises,optional"`
	PressureAltitude         *string  `json:"pressure_altitude,omitempty" parquet:"pressure_altitude,optional"`
	City                     *string  `json:"city,omitempty" parquet:"city,optional"`
	Desc                     *string  `json:"desc,omitempty" parquet:"desc,optional"`
	Isp                      *string  `json:"isp,omitempty" parquet:"isp,optional"`
	Long                     *float64 `json:"long,omitempty" parquet:"long,optional"`
}
