// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Logger struct {
	Device       *Device  `json:"device,omitempty" parquet:"device,optional"`
	EventUid     *string  `json:"event_uid,omitempty" parquet:"event_uid,optional"`
	LogLevel     *string  `json:"log_level,omitempty" parquet:"log_level,optional"`
	LogVersion   *string  `json:"log_version,omitempty" parquet:"log_version,optional"`
	TransmitTime *int64   `json:"transmit_time,omitempty" parquet:"transmit_time,optional"`
	Uid          *string  `json:"uid,omitempty" parquet:"uid,optional"`
	LogName      *string  `json:"log_name,omitempty" parquet:"log_name,optional"`
	LogProvider  *string  `json:"log_provider,omitempty" parquet:"log_provider,optional"`
	LoggedTime   *int64   `json:"logged_time,omitempty" parquet:"logged_time,optional"`
	Name         *string  `json:"name,omitempty" parquet:"name,optional"`
	Product      *Product `json:"product,omitempty" parquet:"product,optional"`
	Version      *string  `json:"version,omitempty" parquet:"version,optional"`
}
