// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type LongString struct {
	IsTruncated     *bool  `json:"is_truncated,omitempty" parquet:"is_truncated,optional"`
	UntruncatedSize *int32 `json:"untruncated_size,omitempty" parquet:"untruncated_size,optional"`
	Value           string `json:"value" parquet:"value"`
}
