// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type ManagedEntity struct {
	Device   *Device       `json:"device,omitempty" parquet:"device,optional"`
	Email    *Email        `json:"email,omitempty" parquet:"email,optional"`
	Org      *Organization `json:"org,omitempty" parquet:"org,optional"`
	TypeId   *int32        `json:"type_id,omitempty" parquet:"type_id,optional"`
	Uid      *string       `json:"uid,omitempty" parquet:"uid,optional"`
	User     *User         `json:"user,omitempty" parquet:"user,optional"`
	Data     *string       `json:"data,omitempty" parquet:"data,optional"`
	Group    *Group        `json:"group,omitempty" parquet:"group,optional"`
	Location *GeoLocation  `json:"location,omitempty" parquet:"location,optional"`
	Name     *string       `json:"name,omitempty" parquet:"name,optional"`
	Policy   *Policy       `json:"policy,omitempty" parquet:"policy,optional"`
	Type     *string       `json:"type,omitempty" parquet:"type,optional"`
	Version  *string       `json:"version,omitempty" parquet:"version,optional"`
}
