// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Metadata struct {
	Tags                []*KeyValueobject     `json:"tags,omitempty" parquet:"tags,optional,list"`
	DataClassifications []*DataClassification `json:"data_classifications,omitempty" parquet:"data_classifications,optional,list"`
	EventCode           *string               `json:"event_code,omitempty" parquet:"event_code,optional"`
	LogName             *string               `json:"log_name,omitempty" parquet:"log_name,optional"`
	LogProvider         *string               `json:"log_provider,omitempty" parquet:"log_provider,optional"`
	LogVersion          *string               `json:"log_version,omitempty" parquet:"log_version,optional"`
	LoggedTime          *int64                `json:"logged_time,omitempty" parquet:"logged_time,optional"`
	ModifiedTime        *int64                `json:"modified_time,omitempty" parquet:"modified_time,optional"`
	OriginalTime        *string               `json:"original_time,omitempty" parquet:"original_time,optional"`
	Profiles            []*string             `json:"profiles,omitempty" parquet:"profiles,optional,list"`
	CorrelationUid      *string               `json:"correlation_uid,omitempty" parquet:"correlation_uid,optional"`
	Extensions          []*SchemaExtension    `json:"extensions,omitempty" parquet:"extensions,optional,list"`
	Labels              []*string             `json:"labels,omitempty" parquet:"labels,optional,list"`
	Loggers             []*Logger             `json:"loggers,omitempty" parquet:"loggers,optional,list"`
	Sequence            *int32                `json:"sequence,omitempty" parquet:"sequence,optional"`
	TenantUid           *string               `json:"tenant_uid,omitempty" parquet:"tenant_uid,optional"`
	Version             string                `json:"version" parquet:"version"`
	Debug               []*string             `json:"debug,omitempty" parquet:"debug,optional,list"`
	LogLevel            *string               `json:"log_level,omitempty" parquet:"log_level,optional"`
	ProcessedTime       *int64                `json:"processed_time,omitempty" parquet:"processed_time,optional"`
	Uid                 *string               `json:"uid,omitempty" parquet:"uid,optional"`
	Product             Product               `json:"product" parquet:"product"`
}
