// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Module struct {
	LoadTypeId   int32   `json:"load_type_id" parquet:"load_type_id"`
	StartAddress *string `json:"start_address,omitempty" parquet:"start_address,optional"`
	Type         *string `json:"type,omitempty" parquet:"type,optional"`
	BaseAddress  *string `json:"base_address,omitempty" parquet:"base_address,optional"`
	File         *File   `json:"file,omitempty" parquet:"file,optional"`
	FunctionName *string `json:"function_name,omitempty" parquet:"function_name,optional"`
	LoadType     *string `json:"load_type,omitempty" parquet:"load_type,optional"`
}
