// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type NetworkEndpoint struct {
	Type             *string               `json:"type,omitempty" parquet:"type,optional"`
	TypeId           *int32                `json:"type_id,omitempty" parquet:"type_id,optional"`
	Mac              *string               `json:"mac,omitempty" parquet:"mac,optional"`
	Os               *OperatingSystemOS    `json:"os,omitempty" parquet:"os,optional"`
	VlanUid          *string               `json:"vlan_uid,omitempty" parquet:"vlan_uid,optional"`
	Zone             *string               `json:"zone,omitempty" parquet:"zone,optional"`
	Container        *Container            `json:"container,omitempty" parquet:"container,optional"`
	AutonomousSystem *AutonomousSystem     `json:"autonomous_system,omitempty" parquet:"autonomous_system,optional"`
	AgentList        []*Agent              `json:"agent_list,omitempty" parquet:"agent_list,optional,list"`
	InstanceUid      *string               `json:"instance_uid,omitempty" parquet:"instance_uid,optional"`
	SubnetUid        *string               `json:"subnet_uid,omitempty" parquet:"subnet_uid,optional"`
	VpcUid           *string               `json:"vpc_uid,omitempty" parquet:"vpc_uid,optional"`
	NamespacePid     *int32                `json:"namespace_pid,omitempty" parquet:"namespace_pid,optional"`
	ProxyEndpoint    *NetworkProxyEndpoint `json:"proxy_endpoint,omitempty" parquet:"proxy_endpoint,optional"`
	SvcName          *string               `json:"svc_name,omitempty" parquet:"svc_name,optional"`
	Domain           *string               `json:"domain,omitempty" parquet:"domain,optional"`
	Hostname         *string               `json:"hostname,omitempty" parquet:"hostname,optional"`
	Ip               *string               `json:"ip,omitempty" parquet:"ip,optional"`
	Name             *string               `json:"name,omitempty" parquet:"name,optional"`
	IntermediateIps  []*string             `json:"intermediate_ips,omitempty" parquet:"intermediate_ips,optional,list"`
	Port             *int32                `json:"port,omitempty" parquet:"port,optional"`
	HwInfo           *DeviceHardwareInfo   `json:"hw_info,omitempty" parquet:"hw_info,optional"`
	InterfaceName    *string               `json:"interface_name,omitempty" parquet:"interface_name,optional"`
	InterfaceUid     *string               `json:"interface_uid,omitempty" parquet:"interface_uid,optional"`
	Location         *GeoLocation          `json:"location,omitempty" parquet:"location,optional"`
	Owner            *User                 `json:"owner,omitempty" parquet:"owner,optional"`
	Uid              *string               `json:"uid,omitempty" parquet:"uid,optional"`
}
