// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type NetworkConnectionQuery struct {
	Count          *int32                       `json:"count,omitempty" parquet:"count,optional"`
	StateId        int32                        `json:"state_id" parquet:"state_id"`
	Severity       *string                      `json:"severity,omitempty" parquet:"severity,optional"`
	Time           int64                        `json:"time" parquet:"time"`
	CategoryName   *string                      `json:"category_name,omitempty" parquet:"category_name,optional"`
	StatusDetail   *string                      `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	TypeName       *string                      `json:"type_name,omitempty" parquet:"type_name,optional"`
	ConnectionInfo NetworkConnectionInformation `json:"connection_info" parquet:"connection_info"`
	State          *string                      `json:"state,omitempty" parquet:"state,optional"`
	EndTime        *int64                       `json:"end_time,omitempty" parquet:"end_time,optional"`
	SeverityId     int32                        `json:"severity_id" parquet:"severity_id"`
	Unmapped       *string                      `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	Duration       *int64                       `json:"duration,omitempty" parquet:"duration,optional"`
	StartTime      *int64                       `json:"start_time,omitempty" parquet:"start_time,optional"`
	StatusCode     *string                      `json:"status_code,omitempty" parquet:"status_code,optional"`
	TimezoneOffset *int32                       `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
	CategoryUid    int32                        `json:"category_uid" parquet:"category_uid"`
	ClassUid       int32                        `json:"class_uid" parquet:"class_uid"`
	Metadata       Metadata                     `json:"metadata" parquet:"metadata"`
	TypeUid        int64                        `json:"type_uid" parquet:"type_uid"`
	Message        *string                      `json:"message,omitempty" parquet:"message,optional"`
	QueryResult    *string                      `json:"query_result,omitempty" parquet:"query_result,optional"`
	QueryResultId  int32                        `json:"query_result_id" parquet:"query_result_id"`
	Enrichments    []*Enrichment                `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	Status         *string                      `json:"status,omitempty" parquet:"status,optional"`
	ActivityName   *string                      `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	Observables    []*Observable                `json:"observables,omitempty" parquet:"observables,optional,list"`
	Process        Process                      `json:"process" parquet:"process"`
	ActivityId     int32                        `json:"activity_id" parquet:"activity_id"`
	QueryInfo      *QueryInformation            `json:"query_info,omitempty" parquet:"query_info,optional"`
	ClassName      *string                      `json:"class_name,omitempty" parquet:"class_name,optional"`
	RawData        *string                      `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	StatusId       *int32                       `json:"status_id,omitempty" parquet:"status_id,optional"`
}
