// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type NetworkFileActivity struct {
	Count              *int32                        `json:"count,omitempty" parquet:"count,optional"`
	Observables        []*Observable                 `json:"observables,omitempty" parquet:"observables,optional,list"`
	Status             *string                       `json:"status,omitempty" parquet:"status,optional"`
	Tls                *TransportLayerSecurityTLS    `json:"tls,omitempty" parquet:"tls,optional"`
	StartTime          *int64                        `json:"start_time,omitempty" parquet:"start_time,optional"`
	StatusDetail       *string                       `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	ActivityName       *string                       `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	TypeName           *string                       `json:"type_name,omitempty" parquet:"type_name,optional"`
	ActivityId         int32                         `json:"activity_id" parquet:"activity_id"`
	ClassUid           int32                         `json:"class_uid" parquet:"class_uid"`
	Duration           *int64                        `json:"duration,omitempty" parquet:"duration,optional"`
	Message            *string                       `json:"message,omitempty" parquet:"message,optional"`
	StatusId           *int32                        `json:"status_id,omitempty" parquet:"status_id,optional"`
	ConnectionInfo     *NetworkConnectionInformation `json:"connection_info,omitempty" parquet:"connection_info,optional"`
	DstEndpoint        *NetworkEndpoint              `json:"dst_endpoint,omitempty" parquet:"dst_endpoint,optional"`
	Ja4FingerprintList []*JA4Fingerprint             `json:"ja4_fingerprint_list,omitempty" parquet:"ja4_fingerprint_list,optional,list"`
	CategoryName       *string                       `json:"category_name,omitempty" parquet:"category_name,optional"`
	ClassName          *string                       `json:"class_name,omitempty" parquet:"class_name,optional"`
	SeverityId         int32                         `json:"severity_id" parquet:"severity_id"`
	StatusCode         *string                       `json:"status_code,omitempty" parquet:"status_code,optional"`
	CategoryUid        int32                         `json:"category_uid" parquet:"category_uid"`
	Enrichments        []*Enrichment                 `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	Severity           *string                       `json:"severity,omitempty" parquet:"severity,optional"`
	Time               int64                         `json:"time" parquet:"time"`
	Metadata           Metadata                      `json:"metadata" parquet:"metadata"`
	TimezoneOffset     *int32                        `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
	TypeUid            int64                         `json:"type_uid" parquet:"type_uid"`
	SrcEndpoint        NetworkEndpoint               `json:"src_endpoint" parquet:"src_endpoint"`
	AppName            *string                       `json:"app_name,omitempty" parquet:"app_name,optional"`
	EndTime            *int64                        `json:"end_time,omitempty" parquet:"end_time,optional"`
	Unmapped           *string                       `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	RawData            *string                       `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	File               File                          `json:"file" parquet:"file"`
	Traffic            *NetworkTraffic               `json:"traffic,omitempty" parquet:"traffic,optional"`
	ExpirationTime     *int64                        `json:"expiration_time,omitempty" parquet:"expiration_time,optional"`
}
