// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type NetworkConnectionInformation struct {
	Direction     *string  `json:"direction,omitempty" parquet:"direction,optional"`
	DirectionId   int32    `json:"direction_id" parquet:"direction_id"`
	FlagHistory   *string  `json:"flag_history,omitempty" parquet:"flag_history,optional"`
	ProtocolName  *string  `json:"protocol_name,omitempty" parquet:"protocol_name,optional"`
	ProtocolNum   *int32   `json:"protocol_num,omitempty" parquet:"protocol_num,optional"`
	ProtocolVer   *string  `json:"protocol_ver,omitempty" parquet:"protocol_ver,optional"`
	CommunityUid  *string  `json:"community_uid,omitempty" parquet:"community_uid,optional"`
	ProtocolVerId *int32   `json:"protocol_ver_id,omitempty" parquet:"protocol_ver_id,optional"`
	Session       *Session `json:"session,omitempty" parquet:"session,optional"`
	TcpFlags      *int32   `json:"tcp_flags,omitempty" parquet:"tcp_flags,optional"`
	Uid           *string  `json:"uid,omitempty" parquet:"uid,optional"`
	Boundary      *string  `json:"boundary,omitempty" parquet:"boundary,optional"`
	BoundaryId    *int32   `json:"boundary_id,omitempty" parquet:"boundary_id,optional"`
}
