// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type NetworkInterface struct {
	Hostname     *string `json:"hostname,omitempty" parquet:"hostname,optional"`
	Namespace    *string `json:"namespace,omitempty" parquet:"namespace,optional"`
	SubnetPrefix *int32  `json:"subnet_prefix,omitempty" parquet:"subnet_prefix,optional"`
	TypeId       int32   `json:"type_id" parquet:"type_id"`
	Uid          *string `json:"uid,omitempty" parquet:"uid,optional"`
	Ip           *string `json:"ip,omitempty" parquet:"ip,optional"`
	Mac          *string `json:"mac,omitempty" parquet:"mac,optional"`
	Name         *string `json:"name,omitempty" parquet:"name,optional"`
	Type         *string `json:"type,omitempty" parquet:"type,optional"`
}
