// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type NetworkTraffic struct {
	Packets     *int64 `json:"packets,omitempty" parquet:"packets,optional"`
	PacketsIn   *int64 `json:"packets_in,omitempty" parquet:"packets_in,optional"`
	BytesMissed *int64 `json:"bytes_missed,omitempty" parquet:"bytes_missed,optional"`
	BytesOut    *int64 `json:"bytes_out,omitempty" parquet:"bytes_out,optional"`
	Chunks      *int64 `json:"chunks,omitempty" parquet:"chunks,optional"`
	PacketsOut  *int64 `json:"packets_out,omitempty" parquet:"packets_out,optional"`
	Bytes       *int64 `json:"bytes,omitempty" parquet:"bytes,optional"`
	BytesIn     *int64 `json:"bytes_in,omitempty" parquet:"bytes_in,optional"`
	ChunksIn    *int64 `json:"chunks_in,omitempty" parquet:"chunks_in,optional"`
	ChunksOut   *int64 `json:"chunks_out,omitempty" parquet:"chunks_out,optional"`
}
