// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Observable struct {
	TypeId     int32       `json:"type_id" parquet:"type_id"`
	Value      *string     `json:"value,omitempty" parquet:"value,optional"`
	Name       *string     `json:"name,omitempty" parquet:"name,optional"`
	Reputation *Reputation `json:"reputation,omitempty" parquet:"reputation,optional"`
	Type       *string     `json:"type,omitempty" parquet:"type,optional"`
}
