// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Organization struct {
	Name   *string `json:"name,omitempty" parquet:"name,optional"`
	OuName *string `json:"ou_name,omitempty" parquet:"ou_name,optional"`
	OuUid  *string `json:"ou_uid,omitempty" parquet:"ou_uid,optional"`
	Uid    *string `json:"uid,omitempty" parquet:"uid,optional"`
}
