// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type OperatingSystemOS struct {
	CpeName       *string `json:"cpe_name,omitempty" parquet:"cpe_name,optional"`
	CpuBits       *int32  `json:"cpu_bits,omitempty" parquet:"cpu_bits,optional"`
	Edition       *string `json:"edition,omitempty" parquet:"edition,optional"`
	SpName        *string `json:"sp_name,omitempty" parquet:"sp_name,optional"`
	SpVer         *int32  `json:"sp_ver,omitempty" parquet:"sp_ver,optional"`
	TypeId        int32   `json:"type_id" parquet:"type_id"`
	Build         *string `json:"build,omitempty" parquet:"build,optional"`
	KernelRelease *string `json:"kernel_release,omitempty" parquet:"kernel_release,optional"`
	Lang          *string `json:"lang,omitempty" parquet:"lang,optional"`
	Name          string  `json:"name" parquet:"name"`
	Type          *string `json:"type,omitempty" parquet:"type,optional"`
	Version       *string `json:"version,omitempty" parquet:"version,optional"`
	Country       *string `json:"country,omitempty" parquet:"country,optional"`
}
