// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type OSINTInventoryInfo struct {
	ClassName      *string       `json:"class_name,omitempty" parquet:"class_name,optional"`
	ClassUid       int32         `json:"class_uid" parquet:"class_uid"`
	Metadata       Metadata      `json:"metadata" parquet:"metadata"`
	Observables    []*Observable `json:"observables,omitempty" parquet:"observables,optional,list"`
	SeverityId     int32         `json:"severity_id" parquet:"severity_id"`
	StatusCode     *string       `json:"status_code,omitempty" parquet:"status_code,optional"`
	CategoryName   *string       `json:"category_name,omitempty" parquet:"category_name,optional"`
	Count          *int32        `json:"count,omitempty" parquet:"count,optional"`
	TypeUid        int64         `json:"type_uid" parquet:"type_uid"`
	Unmapped       *string       `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	ActivityName   *string       `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	StartTime      *int64        `json:"start_time,omitempty" parquet:"start_time,optional"`
	ActivityId     int32         `json:"activity_id" parquet:"activity_id"`
	Message        *string       `json:"message,omitempty" parquet:"message,optional"`
	Status         *string       `json:"status,omitempty" parquet:"status,optional"`
	CategoryUid    int32         `json:"category_uid" parquet:"category_uid"`
	EndTime        *int64        `json:"end_time,omitempty" parquet:"end_time,optional"`
	Severity       *string       `json:"severity,omitempty" parquet:"severity,optional"`
	Time           int64         `json:"time" parquet:"time"`
	TypeName       *string       `json:"type_name,omitempty" parquet:"type_name,optional"`
	Duration       *int64        `json:"duration,omitempty" parquet:"duration,optional"`
	Enrichments    []*Enrichment `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	StatusId       *int32        `json:"status_id,omitempty" parquet:"status_id,optional"`
	RawData        *string       `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	StatusDetail   *string       `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	TimezoneOffset *int32        `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
}
