// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type OSINT struct {
	File             *File                   `json:"file,omitempty" parquet:"file,optional"`
	Subnet           *string                 `json:"subnet,omitempty" parquet:"subnet,optional"`
	Tlp              *string                 `json:"tlp,omitempty" parquet:"tlp,optional"`
	Type             *string                 `json:"type,omitempty" parquet:"type,optional"`
	VendorName       *string                 `json:"vendor_name,omitempty" parquet:"vendor_name,optional"`
	Vulnerabilities  []*VulnerabilityDetails `json:"vulnerabilities,omitempty" parquet:"vulnerabilities,optional,list"`
	Whois            *WHOIS                  `json:"whois,omitempty" parquet:"whois,optional"`
	Name             *string                 `json:"name,omitempty" parquet:"name,optional"`
	AutonomousSystem *AutonomousSystem       `json:"autonomous_system,omitempty" parquet:"autonomous_system,optional"`
	Email            *Email                  `json:"email,omitempty" parquet:"email,optional"`
	Signatures       []*DigitalSignature     `json:"signatures,omitempty" parquet:"signatures,optional,list"`
	TypeId           int32                   `json:"type_id" parquet:"type_id"`
	Value            string                  `json:"value" parquet:"value"`
	Answers          []*DNSAnswer            `json:"answers,omitempty" parquet:"answers,optional,list"`
	Attacks          []*MITREATTCK           `json:"attacks,omitempty" parquet:"attacks,optional,list"`
	ConfidenceId     *int32                  `json:"confidence_id,omitempty" parquet:"confidence_id,optional"`
	Location         *GeoLocation            `json:"location,omitempty" parquet:"location,optional"`
	Reputation       *Reputation             `json:"reputation,omitempty" parquet:"reputation,optional"`
	Uid              *string                 `json:"uid,omitempty" parquet:"uid,optional"`
	Comment          *string                 `json:"comment,omitempty" parquet:"comment,optional"`
	Confidence       *string                 `json:"confidence,omitempty" parquet:"confidence,optional"`
	EmailAuth        *EmailAuthentication    `json:"email_auth,omitempty" parquet:"email_auth,optional"`
	KillChain        []*KillChainPhase       `json:"kill_chain,omitempty" parquet:"kill_chain,optional,list"`
	RelatedAnalytics []*Analytic             `json:"related_analytics,omitempty" parquet:"related_analytics,optional,list"`
	Script           *Script                 `json:"script,omitempty" parquet:"script,optional"`
	SrcUrl           *string                 `json:"src_url,omitempty" parquet:"src_url,optional"`
	Subdomains       []*string               `json:"subdomains,omitempty" parquet:"subdomains,optional,list"`
}
