// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type SoftwarePackage struct {
	Architecture *string      `json:"architecture,omitempty" parquet:"architecture,optional"`
	CpeName      *string      `json:"cpe_name,omitempty" parquet:"cpe_name,optional"`
	Epoch        *int32       `json:"epoch,omitempty" parquet:"epoch,optional"`
	Release      *string      `json:"release,omitempty" parquet:"release,optional"`
	VendorName   *string      `json:"vendor_name,omitempty" parquet:"vendor_name,optional"`
	Version      string       `json:"version" parquet:"version"`
	Hash         *Fingerprint `json:"hash,omitempty" parquet:"hash,optional"`
	License      *string      `json:"license,omitempty" parquet:"license,optional"`
	Name         string       `json:"name" parquet:"name"`
	Purl         *string      `json:"purl,omitempty" parquet:"purl,optional"`
	Type         *string      `json:"type,omitempty" parquet:"type,optional"`
	TypeId       *int32       `json:"type_id,omitempty" parquet:"type_id,optional"`
}
