// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type PeripheralDevice struct {
	Model        *string `json:"model,omitempty" parquet:"model,optional"`
	Name         string  `json:"name" parquet:"name"`
	SerialNumber *string `json:"serial_number,omitempty" parquet:"serial_number,optional"`
	Uid          *string `json:"uid,omitempty" parquet:"uid,optional"`
	VendorName   *string `json:"vendor_name,omitempty" parquet:"vendor_name,optional"`
	Class        string  `json:"class" parquet:"class"`
}
