// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Policy struct {
	Group     *Group  `json:"group,omitempty" parquet:"group,optional"`
	IsApplied *bool   `json:"is_applied,omitempty" parquet:"is_applied,optional"`
	Name      *string `json:"name,omitempty" parquet:"name,optional"`
	Uid       *string `json:"uid,omitempty" parquet:"uid,optional"`
	Version   *string `json:"version,omitempty" parquet:"version,optional"`
	Desc      *string `json:"desc,omitempty" parquet:"desc,optional"`
}
