// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Process struct {
	Ancestry             []*ProcessEntity       `json:"ancestry,omitempty" parquet:"ancestry,optional,list"`
	IntegrityId          *int32                 `json:"integrity_id,omitempty" parquet:"integrity_id,optional"`
	Tid                  *int32                 `json:"tid,omitempty" parquet:"tid,optional"`
	Auid                 *int32                 `json:"auid,omitempty" parquet:"auid,optional"`
	Euid                 *int32                 `json:"euid,omitempty" parquet:"euid,optional"`
	Integrity            *string                `json:"integrity,omitempty" parquet:"integrity,optional"`
	Name                 *string                `json:"name,omitempty" parquet:"name,optional"`
	EnvironmentVariables []*EnvironmentVariable `json:"environment_variables,omitempty" parquet:"environment_variables,optional,list"`
	Session              *Session               `json:"session,omitempty" parquet:"session,optional"`
	TerminatedTime       *int64                 `json:"terminated_time,omitempty" parquet:"terminated_time,optional"`
	Egid                 *int32                 `json:"egid,omitempty" parquet:"egid,optional"`
	Sandbox              *string                `json:"sandbox,omitempty" parquet:"sandbox,optional"`
	NamespacePid         *int32                 `json:"namespace_pid,omitempty" parquet:"namespace_pid,optional"`
	CreatedTime          *int64                 `json:"created_time,omitempty" parquet:"created_time,optional"`
	User                 *User                  `json:"user,omitempty" parquet:"user,optional"`
	CmdLine              *string                `json:"cmd_line,omitempty" parquet:"cmd_line,optional"`
	Pid                  *int32                 `json:"pid,omitempty" parquet:"pid,optional"`
	Uid                  *string                `json:"uid,omitempty" parquet:"uid,optional"`
	ParentProcess        *Process               `json:"parent_process,omitempty" parquet:"parent_process,optional"`
	Xattributes          *string                `json:"xattributes,omitempty" parquet:"xattributes,optional"`
	Group                *Group                 `json:"group,omitempty" parquet:"group,optional"`
	LoadedModules        []*string              `json:"loaded_modules,omitempty" parquet:"loaded_modules,optional,list"`
	WorkingDirectory     *string                `json:"working_directory,omitempty" parquet:"working_directory,optional"`
	File                 *File                  `json:"file,omitempty" parquet:"file,optional"`
	Container            *Container             `json:"container,omitempty" parquet:"container,optional"`
	Path                 *string                `json:"path,omitempty" parquet:"path,optional"`
}
