// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type ProcessActivity struct {
	SeverityId           int32         `json:"severity_id" parquet:"severity_id"`
	InjectionTypeId      *int32        `json:"injection_type_id,omitempty" parquet:"injection_type_id,optional"`
	ActivityName         *string       `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	Unmapped             *string       `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	ActualPermissions    *int32        `json:"actual_permissions,omitempty" parquet:"actual_permissions,optional"`
	Time                 int64         `json:"time" parquet:"time"`
	TimezoneOffset       *int32        `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
	ExitCode             *int32        `json:"exit_code,omitempty" parquet:"exit_code,optional"`
	TypeName             *string       `json:"type_name,omitempty" parquet:"type_name,optional"`
	CategoryName         *string       `json:"category_name,omitempty" parquet:"category_name,optional"`
	RequestedPermissions *int32        `json:"requested_permissions,omitempty" parquet:"requested_permissions,optional"`
	Observables          []*Observable `json:"observables,omitempty" parquet:"observables,optional,list"`
	Severity             *string       `json:"severity,omitempty" parquet:"severity,optional"`
	StatusDetail         *string       `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	Process              Process       `json:"process" parquet:"process"`
	TypeUid              int64         `json:"type_uid" parquet:"type_uid"`
	Message              *string       `json:"message,omitempty" parquet:"message,optional"`
	ClassName            *string       `json:"class_name,omitempty" parquet:"class_name,optional"`
	ClassUid             int32         `json:"class_uid" parquet:"class_uid"`
	StatusId             *int32        `json:"status_id,omitempty" parquet:"status_id,optional"`
	ActivityId           int32         `json:"activity_id" parquet:"activity_id"`
	InjectionType        *string       `json:"injection_type,omitempty" parquet:"injection_type,optional"`
	Duration             *int64        `json:"duration,omitempty" parquet:"duration,optional"`
	StartTime            *int64        `json:"start_time,omitempty" parquet:"start_time,optional"`
	Status               *string       `json:"status,omitempty" parquet:"status,optional"`
	CategoryUid          int32         `json:"category_uid" parquet:"category_uid"`
	Module               *Module       `json:"module,omitempty" parquet:"module,optional"`
	Count                *int32        `json:"count,omitempty" parquet:"count,optional"`
	EndTime              *int64        `json:"end_time,omitempty" parquet:"end_time,optional"`
	RawData              *string       `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	StatusCode           *string       `json:"status_code,omitempty" parquet:"status_code,optional"`
	Enrichments          []*Enrichment `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	Metadata             Metadata      `json:"metadata" parquet:"metadata"`
}
