// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type ProcessEntity struct {
	CmdLine     *string `json:"cmd_line,omitempty" parquet:"cmd_line,optional"`
	CreatedTime *int64  `json:"created_time,omitempty" parquet:"created_time,optional"`
	Name        *string `json:"name,omitempty" parquet:"name,optional"`
	Path        *string `json:"path,omitempty" parquet:"path,optional"`
	Pid         *int32  `json:"pid,omitempty" parquet:"pid,optional"`
	Uid         *string `json:"uid,omitempty" parquet:"uid,optional"`
}
