// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Product struct {
	Feature             *Feature              `json:"feature,omitempty" parquet:"feature,optional"`
	Lang                *string               `json:"lang,omitempty" parquet:"lang,optional"`
	Name                *string               `json:"name,omitempty" parquet:"name,optional"`
	Uid                 *string               `json:"uid,omitempty" parquet:"uid,optional"`
	DataClassifications []*DataClassification `json:"data_classifications,omitempty" parquet:"data_classifications,optional,list"`
	CpeName             *string               `json:"cpe_name,omitempty" parquet:"cpe_name,optional"`
	Path                *string               `json:"path,omitempty" parquet:"path,optional"`
	UrlString           *string               `json:"url_string,omitempty" parquet:"url_string,optional"`
	VendorName          *string               `json:"vendor_name,omitempty" parquet:"vendor_name,optional"`
	Version             *string               `json:"version,omitempty" parquet:"version,optional"`
}
