// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type QueryInformation struct {
	Bytes       *int64  `json:"bytes,omitempty" parquet:"bytes,optional"`
	Data        *string `json:"data,omitempty" parquet:"data,optional"`
	Name        *string `json:"name,omitempty" parquet:"name,optional"`
	QueryString string  `json:"query_string" parquet:"query_string"`
	QueryTime   *int64  `json:"query_time,omitempty" parquet:"query_time,optional"`
	Uid         *string `json:"uid,omitempty" parquet:"uid,optional"`
}
