// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type RDPActivity struct {
	ClassName          *string                       `json:"class_name,omitempty" parquet:"class_name,optional"`
	Enrichments        []*Enrichment                 `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	RawData            *string                       `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	SeverityId         int32                         `json:"severity_id" parquet:"severity_id"`
	TypeName           *string                       `json:"type_name,omitempty" parquet:"type_name,optional"`
	File               *File                         `json:"file,omitempty" parquet:"file,optional"`
	Duration           *int64                        `json:"duration,omitempty" parquet:"duration,optional"`
	Time               int64                         `json:"time" parquet:"time"`
	Capabilities       []*string                     `json:"capabilities,omitempty" parquet:"capabilities,optional,list"`
	Ja4FingerprintList []*JA4Fingerprint             `json:"ja4_fingerprint_list,omitempty" parquet:"ja4_fingerprint_list,optional,list"`
	ActivityName       *string                       `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	TypeUid            int64                         `json:"type_uid" parquet:"type_uid"`
	AppName            *string                       `json:"app_name,omitempty" parquet:"app_name,optional"`
	Message            *string                       `json:"message,omitempty" parquet:"message,optional"`
	CertificateChain   []*string                     `json:"certificate_chain,omitempty" parquet:"certificate_chain,optional,list"`
	Response           *ResponseElements             `json:"response,omitempty" parquet:"response,optional"`
	Status             *string                       `json:"status,omitempty" parquet:"status,optional"`
	Unmapped           *string                       `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	ProtocolVer        *string                       `json:"protocol_ver,omitempty" parquet:"protocol_ver,optional"`
	DstEndpoint        *NetworkEndpoint              `json:"dst_endpoint,omitempty" parquet:"dst_endpoint,optional"`
	Count              *int32                        `json:"count,omitempty" parquet:"count,optional"`
	Traffic            *NetworkTraffic               `json:"traffic,omitempty" parquet:"traffic,optional"`
	ClassUid           int32                         `json:"class_uid" parquet:"class_uid"`
	Severity           *string                       `json:"severity,omitempty" parquet:"severity,optional"`
	IdentifierCookie   *string                       `json:"identifier_cookie,omitempty" parquet:"identifier_cookie,optional"`
	StatusCode         *string                       `json:"status_code,omitempty" parquet:"status_code,optional"`
	Tls                *TransportLayerSecurityTLS    `json:"tls,omitempty" parquet:"tls,optional"`
	CategoryName       *string                       `json:"category_name,omitempty" parquet:"category_name,optional"`
	KeyboardInfo       *KeyboardInformation          `json:"keyboard_info,omitempty" parquet:"keyboard_info,optional"`
	Metadata           Metadata                      `json:"metadata" parquet:"metadata"`
	RemoteDisplay      *Display                      `json:"remote_display,omitempty" parquet:"remote_display,optional"`
	Request            *RequestElements              `json:"request,omitempty" parquet:"request,optional"`
	EndTime            *int64                        `json:"end_time,omitempty" parquet:"end_time,optional"`
	Observables        []*Observable                 `json:"observables,omitempty" parquet:"observables,optional,list"`
	StatusId           *int32                        `json:"status_id,omitempty" parquet:"status_id,optional"`
	SrcEndpoint        *NetworkEndpoint              `json:"src_endpoint,omitempty" parquet:"src_endpoint,optional"`
	StatusDetail       *string                       `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	TimezoneOffset     *int32                        `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
	CategoryUid        int32                         `json:"category_uid" parquet:"category_uid"`
	ActivityId         int32                         `json:"activity_id" parquet:"activity_id"`
	ConnectionInfo     *NetworkConnectionInformation `json:"connection_info,omitempty" parquet:"connection_info,optional"`
	StartTime          *int64                        `json:"start_time,omitempty" parquet:"start_time,optional"`
}
