// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type RegistryKey struct {
	IsSystem           *bool   `json:"is_system,omitempty" parquet:"is_system,optional"`
	ModifiedTime       *int64  `json:"modified_time,omitempty" parquet:"modified_time,optional"`
	Path               string  `json:"path" parquet:"path"`
	SecurityDescriptor *string `json:"security_descriptor,omitempty" parquet:"security_descriptor,optional"`
}
