// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type RegistryValue struct {
	Data         *string `json:"data,omitempty" parquet:"data,optional"`
	IsDefault    *bool   `json:"is_default,omitempty" parquet:"is_default,optional"`
	ModifiedTime *int64  `json:"modified_time,omitempty" parquet:"modified_time,optional"`
	Name         string  `json:"name" parquet:"name"`
	Type         *string `json:"type,omitempty" parquet:"type,optional"`
	TypeId       *int32  `json:"type_id,omitempty" parquet:"type_id,optional"`
	IsSystem     *bool   `json:"is_system,omitempty" parquet:"is_system,optional"`
	Path         string  `json:"path" parquet:"path"`
}
