// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type RelatedEventFinding struct {
	CreatedTime   *int64            `json:"created_time,omitempty" parquet:"created_time,optional"`
	Desc          *string           `json:"desc,omitempty" parquet:"desc,optional"`
	LastSeenTime  *int64            `json:"last_seen_time,omitempty" parquet:"last_seen_time,optional"`
	Product       *Product          `json:"product,omitempty" parquet:"product,optional"`
	Count         *int32            `json:"count,omitempty" parquet:"count,optional"`
	ModifiedTime  *int64            `json:"modified_time,omitempty" parquet:"modified_time,optional"`
	Severity      *string           `json:"severity,omitempty" parquet:"severity,optional"`
	SeverityId    *int32            `json:"severity_id,omitempty" parquet:"severity_id,optional"`
	Tags          []*KeyValueobject `json:"tags,omitempty" parquet:"tags,optional,list"`
	Title         *string           `json:"title,omitempty" parquet:"title,optional"`
	TypeName      *string           `json:"type_name,omitempty" parquet:"type_name,optional"`
	Attacks       []*MITREATTCK     `json:"attacks,omitempty" parquet:"attacks,optional,list"`
	FirstSeenTime *int64            `json:"first_seen_time,omitempty" parquet:"first_seen_time,optional"`
	Type          *string           `json:"type,omitempty" parquet:"type,optional"`
	Uid           string            `json:"uid" parquet:"uid"`
	KillChain     []*KillChainPhase `json:"kill_chain,omitempty" parquet:"kill_chain,optional,list"`
	Observables   []*Observable     `json:"observables,omitempty" parquet:"observables,optional,list"`
	TypeUid       *int64            `json:"type_uid,omitempty" parquet:"type_uid,optional"`
}
