// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Remediation struct {
	Desc          string       `json:"desc" parquet:"desc"`
	KbArticleList []*KBArticle `json:"kb_article_list,omitempty" parquet:"kb_article_list,optional,list"`
	References    []*string    `json:"references,omitempty" parquet:"references,optional,list"`
}
