// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Reputation struct {
	BaseScore float64 `json:"base_score" parquet:"base_score"`
	Provider  *string `json:"provider,omitempty" parquet:"provider,optional"`
	Score     *string `json:"score,omitempty" parquet:"score,optional"`
	ScoreId   int32   `json:"score_id" parquet:"score_id"`
}
