// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type RequestElements struct {
	Uid        string       `json:"uid" parquet:"uid"`
	Containers []*Container `json:"containers,omitempty" parquet:"containers,optional,list"`
	Data       *string      `json:"data,omitempty" parquet:"data,optional"`
	Flags      []*string    `json:"flags,omitempty" parquet:"flags,optional,list"`
}
