// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type ResourceDetails struct {
	Hostname            *string               `json:"hostname,omitempty" parquet:"hostname,optional"`
	Namespace           *string               `json:"namespace,omitempty" parquet:"namespace,optional"`
	Version             *string               `json:"version,omitempty" parquet:"version,optional"`
	AgentList           []*Agent              `json:"agent_list,omitempty" parquet:"agent_list,optional,list"`
	CloudPartition      *string               `json:"cloud_partition,omitempty" parquet:"cloud_partition,optional"`
	Criticality         *string               `json:"criticality,omitempty" parquet:"criticality,optional"`
	Name                *string               `json:"name,omitempty" parquet:"name,optional"`
	Owner               *User                 `json:"owner,omitempty" parquet:"owner,optional"`
	Data                *string               `json:"data,omitempty" parquet:"data,optional"`
	Type                *string               `json:"type,omitempty" parquet:"type,optional"`
	Ip                  *string               `json:"ip,omitempty" parquet:"ip,optional"`
	Labels              []*string             `json:"labels,omitempty" parquet:"labels,optional,list"`
	Tags                []*KeyValueobject     `json:"tags,omitempty" parquet:"tags,optional,list"`
	Uid                 *string               `json:"uid,omitempty" parquet:"uid,optional"`
	Region              *string               `json:"region,omitempty" parquet:"region,optional"`
	DataClassifications []*DataClassification `json:"data_classifications,omitempty" parquet:"data_classifications,optional,list"`
	Group               *Group                `json:"group,omitempty" parquet:"group,optional"`
}
