// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type ResponseElements struct {
	ErrorMessage *string      `json:"error_message,omitempty" parquet:"error_message,optional"`
	Flags        []*string    `json:"flags,omitempty" parquet:"flags,optional,list"`
	Message      *string      `json:"message,omitempty" parquet:"message,optional"`
	Code         *int32       `json:"code,omitempty" parquet:"code,optional"`
	Containers   []*Container `json:"containers,omitempty" parquet:"containers,optional,list"`
	Data         *string      `json:"data,omitempty" parquet:"data,optional"`
	Error        *string      `json:"error,omitempty" parquet:"error,optional"`
}
