// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type RPCInterface struct {
	AckResult *int32 `json:"ack_result,omitempty" parquet:"ack_result,optional"`
	Uuid      string `json:"uuid" parquet:"uuid"`
	Version   string `json:"version" parquet:"version"`
	AckReason *int32 `json:"ack_reason,omitempty" parquet:"ack_reason,optional"`
}
