// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Rule struct {
	Name     *string `json:"name,omitempty" parquet:"name,optional"`
	Type     *string `json:"type,omitempty" parquet:"type,optional"`
	Uid      *string `json:"uid,omitempty" parquet:"uid,optional"`
	Version  *string `json:"version,omitempty" parquet:"version,optional"`
	Category *string `json:"category,omitempty" parquet:"category,optional"`
	Desc     *string `json:"desc,omitempty" parquet:"desc,optional"`
}
