// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type SoftwareBillofMaterials struct {
	CreatedTime        *int64              `json:"created_time,omitempty" parquet:"created_time,optional"`
	Package            SoftwarePackage     `json:"package" parquet:"package"`
	Product            *Product            `json:"product,omitempty" parquet:"product,optional"`
	SoftwareComponents []SoftwareComponent `json:"software_components" parquet:"software_components,list"`
}
