// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Scan struct {
	Name   *string `json:"name,omitempty" parquet:"name,optional"`
	Type   *string `json:"type,omitempty" parquet:"type,optional"`
	TypeId int32   `json:"type_id" parquet:"type_id"`
	Uid    *string `json:"uid,omitempty" parquet:"uid,optional"`
}
