// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type ScanActivity struct {
	NumResolutions   *int32        `json:"num_resolutions,omitempty" parquet:"num_resolutions,optional"`
	NumSkippedItems  *int32        `json:"num_skipped_items,omitempty" parquet:"num_skipped_items,optional"`
	Metadata         Metadata      `json:"metadata" parquet:"metadata"`
	Status           *string       `json:"status,omitempty" parquet:"status,optional"`
	TypeName         *string       `json:"type_name,omitempty" parquet:"type_name,optional"`
	Severity         *string       `json:"severity,omitempty" parquet:"severity,optional"`
	StatusCode       *string       `json:"status_code,omitempty" parquet:"status_code,optional"`
	StatusId         *int32        `json:"status_id,omitempty" parquet:"status_id,optional"`
	RawData          *string       `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	Time             int64         `json:"time" parquet:"time"`
	ActivityName     *string       `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	NumTrustedItems  *int32        `json:"num_trusted_items,omitempty" parquet:"num_trusted_items,optional"`
	StartTime        *int64        `json:"start_time,omitempty" parquet:"start_time,optional"`
	CategoryName     *string       `json:"category_name,omitempty" parquet:"category_name,optional"`
	ClassUid         int32         `json:"class_uid" parquet:"class_uid"`
	Message          *string       `json:"message,omitempty" parquet:"message,optional"`
	NumDetections    *int32        `json:"num_detections,omitempty" parquet:"num_detections,optional"`
	ScheduleUid      *string       `json:"schedule_uid,omitempty" parquet:"schedule_uid,optional"`
	CategoryUid      int32         `json:"category_uid" parquet:"category_uid"`
	Observables      []*Observable `json:"observables,omitempty" parquet:"observables,optional,list"`
	TimezoneOffset   *int32        `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
	TypeUid          int64         `json:"type_uid" parquet:"type_uid"`
	Unmapped         *string       `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	Duration         *int64        `json:"duration,omitempty" parquet:"duration,optional"`
	NumFolders       *int32        `json:"num_folders,omitempty" parquet:"num_folders,optional"`
	Total            *int32        `json:"total,omitempty" parquet:"total,optional"`
	SeverityId       int32         `json:"severity_id" parquet:"severity_id"`
	NumFiles         *int32        `json:"num_files,omitempty" parquet:"num_files,optional"`
	StatusDetail     *string       `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	EndTime          *int64        `json:"end_time,omitempty" parquet:"end_time,optional"`
	CommandUid       *string       `json:"command_uid,omitempty" parquet:"command_uid,optional"`
	Enrichments      []*Enrichment `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	ActivityId       int32         `json:"activity_id" parquet:"activity_id"`
	NumProcesses     *int32        `json:"num_processes,omitempty" parquet:"num_processes,optional"`
	NumRegistryItems *int32        `json:"num_registry_items,omitempty" parquet:"num_registry_items,optional"`
	Scan             Scan          `json:"scan" parquet:"scan"`
	ClassName        *string       `json:"class_name,omitempty" parquet:"class_name,optional"`
	NumNetworkItems  *int32        `json:"num_network_items,omitempty" parquet:"num_network_items,optional"`
	Count            *int32        `json:"count,omitempty" parquet:"count,optional"`
}
