// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type SCIM struct {
	Version                    *string `json:"version,omitempty" parquet:"version,optional"`
	AuthProtocolId             *int32  `json:"auth_protocol_id,omitempty" parquet:"auth_protocol_id,optional"`
	LastRunTime                *int64  `json:"last_run_time,omitempty" parquet:"last_run_time,optional"`
	ScimUserSchema             *string `json:"scim_user_schema,omitempty" parquet:"scim_user_schema,optional"`
	StateId                    *int32  `json:"state_id,omitempty" parquet:"state_id,optional"`
	UrlString                  *string `json:"url_string,omitempty" parquet:"url_string,optional"`
	CreatedTime                *int64  `json:"created_time,omitempty" parquet:"created_time,optional"`
	ErrorMessage               *string `json:"error_message,omitempty" parquet:"error_message,optional"`
	State                      *string `json:"state,omitempty" parquet:"state,optional"`
	AuthProtocol               *string `json:"auth_protocol,omitempty" parquet:"auth_protocol,optional"`
	IsUserProvisioningEnabled  *bool   `json:"is_user_provisioning_enabled,omitempty" parquet:"is_user_provisioning_enabled,optional"`
	RateLimit                  *int32  `json:"rate_limit,omitempty" parquet:"rate_limit,optional"`
	UidAlt                     *string `json:"uid_alt,omitempty" parquet:"uid_alt,optional"`
	VendorName                 *string `json:"vendor_name,omitempty" parquet:"vendor_name,optional"`
	IsGroupProvisioningEnabled *bool   `json:"is_group_provisioning_enabled,omitempty" parquet:"is_group_provisioning_enabled,optional"`
	ModifiedTime               *int64  `json:"modified_time,omitempty" parquet:"modified_time,optional"`
	Name                       *string `json:"name,omitempty" parquet:"name,optional"`
	ProtocolName               *string `json:"protocol_name,omitempty" parquet:"protocol_name,optional"`
	ScimGroupSchema            *string `json:"scim_group_schema,omitempty" parquet:"scim_group_schema,optional"`
	Uid                        *string `json:"uid,omitempty" parquet:"uid,optional"`
}
