// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Script struct {
	ScriptContent LongString     `json:"script_content" parquet:"script_content"`
	Type          *string        `json:"type,omitempty" parquet:"type,optional"`
	TypeId        int32          `json:"type_id" parquet:"type_id"`
	Uid           *string        `json:"uid,omitempty" parquet:"uid,optional"`
	File          *File          `json:"file,omitempty" parquet:"file,optional"`
	Hashes        []*Fingerprint `json:"hashes,omitempty" parquet:"hashes,optional,list"`
	Name          *string        `json:"name,omitempty" parquet:"name,optional"`
	ParentUid     *string        `json:"parent_uid,omitempty" parquet:"parent_uid,optional"`
}
