// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type SecurityState struct {
	State   *string `json:"state,omitempty" parquet:"state,optional"`
	StateId *int32  `json:"state_id,omitempty" parquet:"state_id,optional"`
}
