// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type SecurityFinding struct {
	Vulnerabilities []*VulnerabilityDetails `json:"vulnerabilities,omitempty" parquet:"vulnerabilities,optional,list"`
	ClassName       *string                 `json:"class_name,omitempty" parquet:"class_name,optional"`
	State           *string                 `json:"state,omitempty" parquet:"state,optional"`
	Metadata        Metadata                `json:"metadata" parquet:"metadata"`
	SeverityId      int32                   `json:"severity_id" parquet:"severity_id"`
	CisCsc          []*CISCSC               `json:"cis_csc,omitempty" parquet:"cis_csc,optional,list"`
	Message         *string                 `json:"message,omitempty" parquet:"message,optional"`
	TypeName        *string                 `json:"type_name,omitempty" parquet:"type_name,optional"`
	TypeUid         int64                   `json:"type_uid" parquet:"type_uid"`
	Resources       []*ResourceDetails      `json:"resources,omitempty" parquet:"resources,optional,list"`
	Finding         Finding                 `json:"finding" parquet:"finding"`
	Process         *Process                `json:"process,omitempty" parquet:"process,optional"`
	Impact          *string                 `json:"impact,omitempty" parquet:"impact,optional"`
	Unmapped        *string                 `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	Analytic        *Analytic               `json:"analytic,omitempty" parquet:"analytic,optional"`
	ImpactScore     *int32                  `json:"impact_score,omitempty" parquet:"impact_score,optional"`
	ClassUid        int32                   `json:"class_uid" parquet:"class_uid"`
	StateId         int32                   `json:"state_id" parquet:"state_id"`
	ActivityId      int32                   `json:"activity_id" parquet:"activity_id"`
	ImpactId        *int32                  `json:"impact_id,omitempty" parquet:"impact_id,optional"`
	Severity        *string                 `json:"severity,omitempty" parquet:"severity,optional"`
	StartTime       *int64                  `json:"start_time,omitempty" parquet:"start_time,optional"`
	Duration        *int64                  `json:"duration,omitempty" parquet:"duration,optional"`
	StatusDetail    *string                 `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	KillChain       []*KillChainPhase       `json:"kill_chain,omitempty" parquet:"kill_chain,optional,list"`
	Status          *string                 `json:"status,omitempty" parquet:"status,optional"`
	StatusId        *int32                  `json:"status_id,omitempty" parquet:"status_id,optional"`
	TimezoneOffset  *int32                  `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
	Compliance      *Compliance             `json:"compliance,omitempty" parquet:"compliance,optional"`
	ActivityName    *string                 `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	CategoryUid     int32                   `json:"category_uid" parquet:"category_uid"`
	EndTime         *int64                  `json:"end_time,omitempty" parquet:"end_time,optional"`
	Enrichments     []*Enrichment           `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	Observables     []*Observable           `json:"observables,omitempty" parquet:"observables,optional,list"`
	CategoryName    *string                 `json:"category_name,omitempty" parquet:"category_name,optional"`
	Count           *int32                  `json:"count,omitempty" parquet:"count,optional"`
	RawData         *string                 `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	DataSources     []*string               `json:"data_sources,omitempty" parquet:"data_sources,optional,list"`
	Nist            []*string               `json:"nist,omitempty" parquet:"nist,optional,list"`
	StatusCode      *string                 `json:"status_code,omitempty" parquet:"status_code,optional"`
	Time            int64                   `json:"time" parquet:"time"`
}
