// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Service struct {
	Version *string           `json:"version,omitempty" parquet:"version,optional"`
	Labels  []*string         `json:"labels,omitempty" parquet:"labels,optional,list"`
	Name    *string           `json:"name,omitempty" parquet:"name,optional"`
	Tags    []*KeyValueobject `json:"tags,omitempty" parquet:"tags,optional,list"`
	Uid     *string           `json:"uid,omitempty" parquet:"uid,optional"`
}
