// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Session struct {
	UidAlt           *string `json:"uid_alt,omitempty" parquet:"uid_alt,optional"`
	CredentialUid    *string `json:"credential_uid,omitempty" parquet:"credential_uid,optional"`
	Terminal         *string `json:"terminal,omitempty" parquet:"terminal,optional"`
	Uid              *string `json:"uid,omitempty" parquet:"uid,optional"`
	ExpirationTime   *int64  `json:"expiration_time,omitempty" parquet:"expiration_time,optional"`
	IsMfa            *bool   `json:"is_mfa,omitempty" parquet:"is_mfa,optional"`
	IsVpn            *bool   `json:"is_vpn,omitempty" parquet:"is_vpn,optional"`
	Uuid             *string `json:"uuid,omitempty" parquet:"uuid,optional"`
	Count            *int32  `json:"count,omitempty" parquet:"count,optional"`
	CreatedTime      *int64  `json:"created_time,omitempty" parquet:"created_time,optional"`
	ExpirationReason *string `json:"expiration_reason,omitempty" parquet:"expiration_reason,optional"`
	IsRemote         *bool   `json:"is_remote,omitempty" parquet:"is_remote,optional"`
	Issuer           *string `json:"issuer,omitempty" parquet:"issuer,optional"`
}
