// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type SoftwareComponent struct {
	RelatedComponent *string      `json:"related_component,omitempty" parquet:"related_component,optional"`
	Relationship     *string      `json:"relationship,omitempty" parquet:"relationship,optional"`
	RelationshipId   *int32       `json:"relationship_id,omitempty" parquet:"relationship_id,optional"`
	TypeId           *int32       `json:"type_id,omitempty" parquet:"type_id,optional"`
	Author           *string      `json:"author,omitempty" parquet:"author,optional"`
	Name             string       `json:"name" parquet:"name"`
	Type             *string      `json:"type,omitempty" parquet:"type,optional"`
	Version          string       `json:"version" parquet:"version"`
	Hash             *Fingerprint `json:"hash,omitempty" parquet:"hash,optional"`
	License          *string      `json:"license,omitempty" parquet:"license,optional"`
	Purl             *string      `json:"purl,omitempty" parquet:"purl,optional"`
}
