// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Span struct {
	EndTime    int64    `json:"end_time" parquet:"end_time"`
	Message    *string  `json:"message,omitempty" parquet:"message,optional"`
	Operation  *string  `json:"operation,omitempty" parquet:"operation,optional"`
	ParentUid  *string  `json:"parent_uid,omitempty" parquet:"parent_uid,optional"`
	Uid        string   `json:"uid" parquet:"uid"`
	Service    *Service `json:"service,omitempty" parquet:"service,optional"`
	StartTime  int64    `json:"start_time" parquet:"start_time"`
	StatusCode *string  `json:"status_code,omitempty" parquet:"status_code,optional"`
	Duration   *int64   `json:"duration,omitempty" parquet:"duration,optional"`
}
