// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type SSO struct {
	AuthProtocolId   *int32              `json:"auth_protocol_id,omitempty" parquet:"auth_protocol_id,optional"`
	Certificate      *DigitalCertificate `json:"certificate,omitempty" parquet:"certificate,optional"`
	IdleTimeout      *int32              `json:"idle_timeout,omitempty" parquet:"idle_timeout,optional"`
	MetadataEndpoint *string             `json:"metadata_endpoint,omitempty" parquet:"metadata_endpoint,optional"`
	ProtocolName     *string             `json:"protocol_name,omitempty" parquet:"protocol_name,optional"`
	Scopes           []*string           `json:"scopes,omitempty" parquet:"scopes,optional,list"`
	LoginEndpoint    *string             `json:"login_endpoint,omitempty" parquet:"login_endpoint,optional"`
	ModifiedTime     *int64              `json:"modified_time,omitempty" parquet:"modified_time,optional"`
	Uid              *string             `json:"uid,omitempty" parquet:"uid,optional"`
	DurationMins     *int32              `json:"duration_mins,omitempty" parquet:"duration_mins,optional"`
	Name             *string             `json:"name,omitempty" parquet:"name,optional"`
	VendorName       *string             `json:"vendor_name,omitempty" parquet:"vendor_name,optional"`
	AuthProtocol     *string             `json:"auth_protocol,omitempty" parquet:"auth_protocol,optional"`
	CreatedTime      *int64              `json:"created_time,omitempty" parquet:"created_time,optional"`
	LogoutEndpoint   *string             `json:"logout_endpoint,omitempty" parquet:"logout_endpoint,optional"`
}
