// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type StartupItem struct {
	RunState    *string          `json:"run_state,omitempty" parquet:"run_state,optional"`
	RunStateId  *int32           `json:"run_state_id,omitempty" parquet:"run_state_id,optional"`
	StartType   *string          `json:"start_type,omitempty" parquet:"start_type,optional"`
	TypeId      *int32           `json:"type_id,omitempty" parquet:"type_id,optional"`
	WinService  *WindowsService  `json:"win_service,omitempty" parquet:"win_service,optional"`
	Driver      *KernelExtension `json:"driver,omitempty" parquet:"driver,optional"`
	Job         *Job             `json:"job,omitempty" parquet:"job,optional"`
	Name        string           `json:"name" parquet:"name"`
	Process     *Process         `json:"process,omitempty" parquet:"process,optional"`
	StartTypeId int32            `json:"start_type_id" parquet:"start_type_id"`
	Type        *string          `json:"type,omitempty" parquet:"type,optional"`
	RunModeIds  []*int32         `json:"run_mode_ids,omitempty" parquet:"run_mode_ids,optional,list"`
	RunModes    []*string        `json:"run_modes,omitempty" parquet:"run_modes,optional,list"`
}
