// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Table struct {
	Groups       []*Group `json:"groups,omitempty" parquet:"groups,optional,list"`
	ModifiedTime *int64   `json:"modified_time,omitempty" parquet:"modified_time,optional"`
	Size         *int64   `json:"size,omitempty" parquet:"size,optional"`
	Uid          *string  `json:"uid,omitempty" parquet:"uid,optional"`
	CreatedTime  *int64   `json:"created_time,omitempty" parquet:"created_time,optional"`
	Desc         *string  `json:"desc,omitempty" parquet:"desc,optional"`
	Name         *string  `json:"name,omitempty" parquet:"name,optional"`
}
