// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type MITREATTCKTechnique struct {
	SrcUrl *string `json:"src_url,omitempty" parquet:"src_url,optional"`
	Uid    *string `json:"uid,omitempty" parquet:"uid,optional"`
	Name   *string `json:"name,omitempty" parquet:"name,optional"`
}
