// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Ticket struct {
	SrcUrl *string `json:"src_url,omitempty" parquet:"src_url,optional"`
	Title  *string `json:"title,omitempty" parquet:"title,optional"`
	Type   *string `json:"type,omitempty" parquet:"type,optional"`
	TypeId *int32  `json:"type_id,omitempty" parquet:"type_id,optional"`
	Uid    *string `json:"uid,omitempty" parquet:"uid,optional"`
}
