// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type TimeSpan struct {
	Duration       *int64  `json:"duration,omitempty" parquet:"duration,optional"`
	DurationDays   *int32  `json:"duration_days,omitempty" parquet:"duration_days,optional"`
	DurationMins   *int32  `json:"duration_mins,omitempty" parquet:"duration_mins,optional"`
	DurationSecs   *int32  `json:"duration_secs,omitempty" parquet:"duration_secs,optional"`
	DurationWeeks  *int32  `json:"duration_weeks,omitempty" parquet:"duration_weeks,optional"`
	Type           *string `json:"type,omitempty" parquet:"type,optional"`
	TypeId         *int32  `json:"type_id,omitempty" parquet:"type_id,optional"`
	DurationHours  *int32  `json:"duration_hours,omitempty" parquet:"duration_hours,optional"`
	DurationMonths *int32  `json:"duration_months,omitempty" parquet:"duration_months,optional"`
	DurationYears  *int32  `json:"duration_years,omitempty" parquet:"duration_years,optional"`
}
