// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type TransportLayerSecurityTLS struct {
	Certificate      *DigitalCertificate `json:"certificate,omitempty" parquet:"certificate,optional"`
	HandshakeDur     *int32              `json:"handshake_dur,omitempty" parquet:"handshake_dur,optional"`
	KeyLength        *int32              `json:"key_length,omitempty" parquet:"key_length,optional"`
	TlsExtensionList []*TLSExtension     `json:"tls_extension_list,omitempty" parquet:"tls_extension_list,optional,list"`
	Alert            *int32              `json:"alert,omitempty" parquet:"alert,optional"`
	CertificateChain []*string           `json:"certificate_chain,omitempty" parquet:"certificate_chain,optional,list"`
	ClientCiphers    []*string           `json:"client_ciphers,omitempty" parquet:"client_ciphers,optional,list"`
	Ja3Hash          *Fingerprint        `json:"ja3_hash,omitempty" parquet:"ja3_hash,optional"`
	Sni              *string             `json:"sni,omitempty" parquet:"sni,optional"`
	Cipher           *string             `json:"cipher,omitempty" parquet:"cipher,optional"`
	Ja3sHash         *Fingerprint        `json:"ja3s_hash,omitempty" parquet:"ja3s_hash,optional"`
	ServerCiphers    []*string           `json:"server_ciphers,omitempty" parquet:"server_ciphers,optional,list"`
	Version          string              `json:"version" parquet:"version"`
}
