// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type TLSExtension struct {
	Data   *string `json:"data,omitempty" parquet:"data,optional"`
	Type   *string `json:"type,omitempty" parquet:"type,optional"`
	TypeId int32   `json:"type_id" parquet:"type_id"`
}
