// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type Trace struct {
	StartTime *int64    `json:"start_time,omitempty" parquet:"start_time,optional"`
	Uid       string    `json:"uid" parquet:"uid"`
	Duration  *int64    `json:"duration,omitempty" parquet:"duration,optional"`
	EndTime   *int64    `json:"end_time,omitempty" parquet:"end_time,optional"`
	Flags     []*string `json:"flags,omitempty" parquet:"flags,optional,list"`
	Service   *Service  `json:"service,omitempty" parquet:"service,optional"`
	Span      *Span     `json:"span,omitempty" parquet:"span,optional"`
}
