// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type TunnelActivity struct {
	Message            *string                       `json:"message,omitempty" parquet:"message,optional"`
	Session            *Session                      `json:"session,omitempty" parquet:"session,optional"`
	Enrichments        []*Enrichment                 `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	Unmapped           *string                       `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	Duration           *int64                        `json:"duration,omitempty" parquet:"duration,optional"`
	StatusCode         *string                       `json:"status_code,omitempty" parquet:"status_code,optional"`
	StatusDetail       *string                       `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	TimezoneOffset     *int32                        `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
	Ja4FingerprintList []*JA4Fingerprint             `json:"ja4_fingerprint_list,omitempty" parquet:"ja4_fingerprint_list,optional,list"`
	Tls                *TransportLayerSecurityTLS    `json:"tls,omitempty" parquet:"tls,optional"`
	ClassUid           int32                         `json:"class_uid" parquet:"class_uid"`
	Status             *string                       `json:"status,omitempty" parquet:"status,optional"`
	Traffic            *NetworkTraffic               `json:"traffic,omitempty" parquet:"traffic,optional"`
	CategoryName       *string                       `json:"category_name,omitempty" parquet:"category_name,optional"`
	Count              *int32                        `json:"count,omitempty" parquet:"count,optional"`
	DstEndpoint        *NetworkEndpoint              `json:"dst_endpoint,omitempty" parquet:"dst_endpoint,optional"`
	ActivityName       *string                       `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	EndTime            *int64                        `json:"end_time,omitempty" parquet:"end_time,optional"`
	TypeUid            int64                         `json:"type_uid" parquet:"type_uid"`
	SrcEndpoint        *NetworkEndpoint              `json:"src_endpoint,omitempty" parquet:"src_endpoint,optional"`
	TunnelType         *string                       `json:"tunnel_type,omitempty" parquet:"tunnel_type,optional"`
	ClassName          *string                       `json:"class_name,omitempty" parquet:"class_name,optional"`
	Metadata           Metadata                      `json:"metadata" parquet:"metadata"`
	ConnectionInfo     *NetworkConnectionInformation `json:"connection_info,omitempty" parquet:"connection_info,optional"`
	CategoryUid        int32                         `json:"category_uid" parquet:"category_uid"`
	Severity           *string                       `json:"severity,omitempty" parquet:"severity,optional"`
	TypeName           *string                       `json:"type_name,omitempty" parquet:"type_name,optional"`
	TunnelInterface    *NetworkInterface             `json:"tunnel_interface,omitempty" parquet:"tunnel_interface,optional"`
	TunnelTypeId       *int32                        `json:"tunnel_type_id,omitempty" parquet:"tunnel_type_id,optional"`
	ProtocolName       *string                       `json:"protocol_name,omitempty" parquet:"protocol_name,optional"`
	StatusId           *int32                        `json:"status_id,omitempty" parquet:"status_id,optional"`
	Time               int64                         `json:"time" parquet:"time"`
	ActivityId         int32                         `json:"activity_id" parquet:"activity_id"`
	AppName            *string                       `json:"app_name,omitempty" parquet:"app_name,optional"`
	Observables        []*Observable                 `json:"observables,omitempty" parquet:"observables,optional,list"`
	User               *User                         `json:"user,omitempty" parquet:"user,optional"`
	RawData            *string                       `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	StartTime          *int64                        `json:"start_time,omitempty" parquet:"start_time,optional"`
	SeverityId         int32                         `json:"severity_id" parquet:"severity_id"`
}
