// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type UnmannedAerialSystem struct {
	HwInfo         *DeviceHardwareInfo `json:"hw_info,omitempty" parquet:"hw_info,optional"`
	Location       *GeoLocation        `json:"location,omitempty" parquet:"location,optional"`
	SerialNumber   *string             `json:"serial_number,omitempty" parquet:"serial_number,optional"`
	UidAlt         *string             `json:"uid_alt,omitempty" parquet:"uid_alt,optional"`
	Model          *string             `json:"model,omitempty" parquet:"model,optional"`
	TrackDirection *string             `json:"track_direction,omitempty" parquet:"track_direction,optional"`
	Name           *string             `json:"name,omitempty" parquet:"name,optional"`
	Type           *string             `json:"type,omitempty" parquet:"type,optional"`
	TypeId         *int32              `json:"type_id,omitempty" parquet:"type_id,optional"`
	Uid            *string             `json:"uid,omitempty" parquet:"uid,optional"`
	Uuid           *string             `json:"uuid,omitempty" parquet:"uuid,optional"`
	Speed          *string             `json:"speed,omitempty" parquet:"speed,optional"`
	SpeedAccuracy  *string             `json:"speed_accuracy,omitempty" parquet:"speed_accuracy,optional"`
	VerticalSpeed  *string             `json:"vertical_speed,omitempty" parquet:"vertical_speed,optional"`
}
