// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type UniformResourceLocator struct {
	Categories   []*string `json:"categories,omitempty" parquet:"categories,optional,list"`
	Hostname     *string   `json:"hostname,omitempty" parquet:"hostname,optional"`
	Path         *string   `json:"path,omitempty" parquet:"path,optional"`
	Port         *int32    `json:"port,omitempty" parquet:"port,optional"`
	QueryString  *string   `json:"query_string,omitempty" parquet:"query_string,optional"`
	UrlString    *string   `json:"url_string,omitempty" parquet:"url_string,optional"`
	CategoryIds  []*int32  `json:"category_ids,omitempty" parquet:"category_ids,optional,list"`
	Domain       *string   `json:"domain,omitempty" parquet:"domain,optional"`
	ResourceType *string   `json:"resource_type,omitempty" parquet:"resource_type,optional"`
	Scheme       *string   `json:"scheme,omitempty" parquet:"scheme,optional"`
	Subdomain    *string   `json:"subdomain,omitempty" parquet:"subdomain,optional"`
}
