// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type User struct {
	HasMfa        *bool         `json:"has_mfa,omitempty" parquet:"has_mfa,optional"`
	PhoneNumber   *string       `json:"phone_number,omitempty" parquet:"phone_number,optional"`
	RiskScore     *int32        `json:"risk_score,omitempty" parquet:"risk_score,optional"`
	Uid           *string       `json:"uid,omitempty" parquet:"uid,optional"`
	ForwardAddr   *string       `json:"forward_addr,omitempty" parquet:"forward_addr,optional"`
	FullName      *string       `json:"full_name,omitempty" parquet:"full_name,optional"`
	Groups        []*Group      `json:"groups,omitempty" parquet:"groups,optional,list"`
	Account       *Account      `json:"account,omitempty" parquet:"account,optional"`
	EmailAddr     *string       `json:"email_addr,omitempty" parquet:"email_addr,optional"`
	LdapPerson    *LDAPPerson   `json:"ldap_person,omitempty" parquet:"ldap_person,optional"`
	RiskLevelId   *int32        `json:"risk_level_id,omitempty" parquet:"risk_level_id,optional"`
	Type          *string       `json:"type,omitempty" parquet:"type,optional"`
	TypeId        *int32        `json:"type_id,omitempty" parquet:"type_id,optional"`
	CredentialUid *string       `json:"credential_uid,omitempty" parquet:"credential_uid,optional"`
	Domain        *string       `json:"domain,omitempty" parquet:"domain,optional"`
	Name          *string       `json:"name,omitempty" parquet:"name,optional"`
	Org           *Organization `json:"org,omitempty" parquet:"org,optional"`
	RiskLevel     *string       `json:"risk_level,omitempty" parquet:"risk_level,optional"`
	UidAlt        *string       `json:"uid_alt,omitempty" parquet:"uid_alt,optional"`
}
