// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type VendorAttributes struct {
	Severity   *string `json:"severity,omitempty" parquet:"severity,optional"`
	SeverityId *int32  `json:"severity_id,omitempty" parquet:"severity_id,optional"`
}
