// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type WebResource struct {
	Tags                []*KeyValueobject     `json:"tags,omitempty" parquet:"tags,optional,list"`
	Data                *string               `json:"data,omitempty" parquet:"data,optional"`
	Desc                *string               `json:"desc,omitempty" parquet:"desc,optional"`
	UrlString           *string               `json:"url_string,omitempty" parquet:"url_string,optional"`
	Labels              []*string             `json:"labels,omitempty" parquet:"labels,optional,list"`
	DataClassifications []*DataClassification `json:"data_classifications,omitempty" parquet:"data_classifications,optional,list"`
	Name                *string               `json:"name,omitempty" parquet:"name,optional"`
	Type                *string               `json:"type,omitempty" parquet:"type,optional"`
	Uid                 *string               `json:"uid,omitempty" parquet:"uid,optional"`
}
