// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type WHOIS struct {
	NameServers      []*string         `json:"name_servers,omitempty" parquet:"name_servers,optional,list"`
	Registrar        *string           `json:"registrar,omitempty" parquet:"registrar,optional"`
	Subnet           *string           `json:"subnet,omitempty" parquet:"subnet,optional"`
	DnssecStatusId   *int32            `json:"dnssec_status_id,omitempty" parquet:"dnssec_status_id,optional"`
	EmailAddr        *string           `json:"email_addr,omitempty" parquet:"email_addr,optional"`
	PhoneNumber      *string           `json:"phone_number,omitempty" parquet:"phone_number,optional"`
	Status           *string           `json:"status,omitempty" parquet:"status,optional"`
	Subdomains       []*string         `json:"subdomains,omitempty" parquet:"subdomains,optional,list"`
	CreatedTime      *int64            `json:"created_time,omitempty" parquet:"created_time,optional"`
	DnssecStatus     *string           `json:"dnssec_status,omitempty" parquet:"dnssec_status,optional"`
	DomainContacts   []*DomainContact  `json:"domain_contacts,omitempty" parquet:"domain_contacts,optional,list"`
	AutonomousSystem *AutonomousSystem `json:"autonomous_system,omitempty" parquet:"autonomous_system,optional"`
	Domain           *string           `json:"domain,omitempty" parquet:"domain,optional"`
	LastSeenTime     *int64            `json:"last_seen_time,omitempty" parquet:"last_seen_time,optional"`
}
