// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type WindowsService struct {
	ServiceCategory       *string           `json:"service_category,omitempty" parquet:"service_category,optional"`
	ServiceCategoryId     *int32            `json:"service_category_id,omitempty" parquet:"service_category_id,optional"`
	ServiceTypeId         *int32            `json:"service_type_id,omitempty" parquet:"service_type_id,optional"`
	Uid                   *string           `json:"uid,omitempty" parquet:"uid,optional"`
	Version               *string           `json:"version,omitempty" parquet:"version,optional"`
	ServiceErrorControlId *int32            `json:"service_error_control_id,omitempty" parquet:"service_error_control_id,optional"`
	ServiceStartTypeId    *int32            `json:"service_start_type_id,omitempty" parquet:"service_start_type_id,optional"`
	ServiceType           *string           `json:"service_type,omitempty" parquet:"service_type,optional"`
	Labels                []*string         `json:"labels,omitempty" parquet:"labels,optional,list"`
	ServiceStartName      *string           `json:"service_start_name,omitempty" parquet:"service_start_name,optional"`
	Tags                  []*KeyValueobject `json:"tags,omitempty" parquet:"tags,optional,list"`
	CmdLine               *string           `json:"cmd_line,omitempty" parquet:"cmd_line,optional"`
	LoadOrderGroup        *string           `json:"load_order_group,omitempty" parquet:"load_order_group,optional"`
	Name                  string            `json:"name" parquet:"name"`
	ServiceDependencies   []*string         `json:"service_dependencies,omitempty" parquet:"service_dependencies,optional,list"`
	ServiceErrorControl   *string           `json:"service_error_control,omitempty" parquet:"service_error_control,optional"`
	ServiceStartType      *string           `json:"service_start_type,omitempty" parquet:"service_start_type,optional"`
}
