// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type WindowsResource struct {
	Details             *string               `json:"details,omitempty" parquet:"details,optional"`
	Name                *string               `json:"name,omitempty" parquet:"name,optional"`
	Type                *string               `json:"type,omitempty" parquet:"type,optional"`
	Uid                 *string               `json:"uid,omitempty" parquet:"uid,optional"`
	Data                *string               `json:"data,omitempty" parquet:"data,optional"`
	Labels              []*string             `json:"labels,omitempty" parquet:"labels,optional,list"`
	Tags                []*KeyValueobject     `json:"tags,omitempty" parquet:"tags,optional,list"`
	SvcName             *string               `json:"svc_name,omitempty" parquet:"svc_name,optional"`
	TypeId              int32                 `json:"type_id" parquet:"type_id"`
	DataClassifications []*DataClassification `json:"data_classifications,omitempty" parquet:"data_classifications,optional,list"`
}
