// autogenerated by scripts/model_gen.go. DO NOT EDIT
package ocsf

type WindowsResourceActivity struct {
	ActivityId     int32           `json:"activity_id" parquet:"activity_id"`
	TypeUid        int64           `json:"type_uid" parquet:"type_uid"`
	Observables    []*Observable   `json:"observables,omitempty" parquet:"observables,optional,list"`
	StatusCode     *string         `json:"status_code,omitempty" parquet:"status_code,optional"`
	Time           int64           `json:"time" parquet:"time"`
	ActivityName   *string         `json:"activity_name,omitempty" parquet:"activity_name,optional"`
	Metadata       Metadata        `json:"metadata" parquet:"metadata"`
	Status         *string         `json:"status,omitempty" parquet:"status,optional"`
	TypeName       *string         `json:"type_name,omitempty" parquet:"type_name,optional"`
	Unmapped       *string         `json:"unmapped,omitempty" parquet:"unmapped,optional"`
	CategoryUid    int32           `json:"category_uid" parquet:"category_uid"`
	ClassUid       int32           `json:"class_uid" parquet:"class_uid"`
	Duration       *int64          `json:"duration,omitempty" parquet:"duration,optional"`
	RawData        *string         `json:"raw_data,omitempty" parquet:"raw_data,optional"`
	Enrichments    []*Enrichment   `json:"enrichments,omitempty" parquet:"enrichments,optional,list"`
	Message        *string         `json:"message,omitempty" parquet:"message,optional"`
	TimezoneOffset *int32          `json:"timezone_offset,omitempty" parquet:"timezone_offset,optional"`
	EndTime        *int64          `json:"end_time,omitempty" parquet:"end_time,optional"`
	CategoryName   *string         `json:"category_name,omitempty" parquet:"category_name,optional"`
	StartTime      *int64          `json:"start_time,omitempty" parquet:"start_time,optional"`
	StatusDetail   *string         `json:"status_detail,omitempty" parquet:"status_detail,optional"`
	Severity       *string         `json:"severity,omitempty" parquet:"severity,optional"`
	SeverityId     int32           `json:"severity_id" parquet:"severity_id"`
	WinResource    WindowsResource `json:"win_resource" parquet:"win_resource"`
	ClassName      *string         `json:"class_name,omitempty" parquet:"class_name,optional"`
	Count          *int32          `json:"count,omitempty" parquet:"count,optional"`
	StatusId       *int32          `json:"status_id,omitempty" parquet:"status_id,optional"`
}
