// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_4_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type MITREDEFENDTechnique struct {

	// Name: The name of the defensive technique. For example: <code>IO Port Restriction</code>.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Source URL: The versioned permalink of the defensive technique. For example: <code>https://d3fend.mitre.org/technique/d3f:IOPortRestriction/</code>.
	SrcUrl *string `json:"src_url,omitempty" parquet:"src_url,optional"`

	// Unique ID: The unique identifier of the defensive technique. For example: <code>D3-IOPR</code>.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`
}

var MITREDEFENDTechniqueFields = []arrow.Field{
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "src_url", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
}

var MITREDEFENDTechniqueStruct = arrow.StructOf(MITREDEFENDTechniqueFields...)

var MITREDEFENDTechniqueSchema = arrow.NewSchema(MITREDEFENDTechniqueFields, nil)
