// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_4_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type Ticket struct {

	// Source URL: The url of a ticket in the ticket system.
	SrcUrl *string `json:"src_url,omitempty" parquet:"src_url,optional"`

	// Title: The title of the ticket.
	Title *string `json:"title,omitempty" parquet:"title,optional"`

	// Ticket Type: The linked ticket type determines whether the ticket is internal or in an external ticketing system.
	Type *string `json:"type,omitempty" parquet:"type,optional"`

	// Ticket Type ID: The normalized identifier for the ticket type.
	TypeId *int32 `json:"type_id,omitempty" parquet:"type_id,optional"`

	// Unique ID: Unique ticket identifier like ticket id.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`
}

var TicketFields = []arrow.Field{
	{Name: "src_url", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "title", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "type_id", Type: arrow.PrimitiveTypes.Int32, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
}

var TicketStruct = arrow.StructOf(TicketFields...)

var TicketSchema = arrow.NewSchema(TicketFields, nil)
var TicketClassname = "ticket"
