// autogenerated by scripts/model_gen.go. DO NOT EDIT
package v1_4_0

import (
	"github.com/apache/arrow-go/v18/arrow"
)

type WebResource struct {

	// Data: Details of the web resource, e.g, <code>file</code> details, <code>search</code> results or application-defined resource.
	Data *string `json:"data,omitempty" parquet:"data,optional"`

	// Data Classification: A list of Data Classification objects, that include information about data classification levels and data category types, indentified by a classifier.
	DataClassifications []*DataClassification `json:"data_classifications,omitempty" parquet:"data_classifications,optional,list"`

	// Description: Description of the web resource.
	Desc *string `json:"desc,omitempty" parquet:"desc,optional"`

	// Labels: The list of labels associated to the resource.
	Labels []string `json:"labels,omitempty" parquet:"labels,optional,list"`

	// Name: The name of the web resource.
	Name *string `json:"name,omitempty" parquet:"name,optional"`

	// Tags: The list of tags; <code>{key:value}</code> pairs associated to the resource.
	Tags []*KeyValueobject `json:"tags,omitempty" parquet:"tags,optional,list"`

	// Type: The web resource type as defined by the event source.
	Type *string `json:"type,omitempty" parquet:"type,optional"`

	// Unique ID: The unique identifier of the web resource.
	Uid *string `json:"uid,omitempty" parquet:"uid,optional"`

	// URL String: The URL pointing towards the source of the web resource.
	UrlString *string `json:"url_string,omitempty" parquet:"url_string,optional"`
}

var WebResourceFields = []arrow.Field{
	{Name: "data", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "data_classifications", Type: arrow.ListOf(DataClassificationStruct), Nullable: true},
	{Name: "desc", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "labels", Type: arrow.ListOf(arrow.BinaryTypes.String), Nullable: true},
	{Name: "name", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "tags", Type: arrow.ListOf(KeyValueobjectStruct), Nullable: true},
	{Name: "type", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "uid", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "url_string", Type: arrow.BinaryTypes.String, Nullable: true},
}

var WebResourceStruct = arrow.StructOf(WebResourceFields...)

var WebResourceSchema = arrow.NewSchema(WebResourceFields, nil)
var WebResourceClassname = "web_resource"
