name: Build DuckDB Iceberg (integrating_rest_api_objects)

on:
  push:
    branches:
      - feature/s3-tables
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout DuckDB Iceberg (with submodules)
        uses: actions/checkout@v4
        with:
          repository: Tishj/duckdb_iceberg
          ref: integrating_rest_api_objects
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3 curl unzip zip pkg-config linux-headers-generic clang cmake build-essential

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git ~/vcpkg
          ~/vcpkg/bootstrap-vcpkg.sh

      - name: Configure environment to use Clang
        run: |
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100
          sudo update-alternatives --set cc /usr/bin/clang
          sudo update-alternatives --set c++ /usr/bin/clang++

      - name: Verify compiler (optional but recommended)
        run: |
          cc --version
          c++ --version

      - name: Build DuckDB Iceberg
        run: |
          VCPKG_TOOLCHAIN_PATH="$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake" \
          EXT_FLAGS="-DCMAKE_POLICY_VERSION_MINIMUM=3.5" \
          make clean release

      - name: Upload DuckDB Iceberg binary
        uses: actions/upload-artifact@v4
        with:
          name: duckdb-iceberg-linux-amd64
          path: build/release/src/libduckdb.so
